apiVersion: v2
name: plausible-analytics
description: A plausible-analytics helm chart

version: 0.8.0

dependencies:
  - name: plausible-analytics
    version: 0.8.0
    repository: https://zekker6.github.io/helm-charts/
