ingress-nginx-fun:
  controller:
    replicaCount: 1
    extraArgs:
      default-ssl-certificate: "ingress-nginx/nginx-fun-default-cert"

    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
        job:
          enabled: false

    service:
      enabled: true
      type: LoadBalancer
      annotations:
        load-balancer.hetzner.cloud/name: "nginx-fun-lb-ingress"
        load-balancer.hetzner.cloud/location: "nbg1"
        load-balancer.hetzner.cloud/type: "lb11"
        load-balancer.hetzner.cloud/use-private-ip: "true"
        load-balancer.hetzner.cloud/ipv6-disabled: "true"
        load-balancer.hetzner.cloud/disable-private-ingress: "true"
        load-balancer.hetzner.cloud/protocol: "tcp"
        load-balancer.hetzner.cloud/hostname: "nginx-fun"
