encValues:  
  api-key: "AgAyINoc7jMPiz0KTTHPg0FZnCIlnMhH4iFhpNOmEgT1WEXK+/M9lHddsFPmXCr0XbWYt/ZBaaUq+hNgOgku5eGpgcqQdvLLzFFZQKYXJt7VS50uWxfPTpPrxFDcarmGH2tjRwMMvBPte8SzpXLWpT5rIwzsCvzZQaNjMobNn2ajvyuDiO5PoTxqFJFByh9kGve3fhFSdMf3BA/c9QaQIu0u3f/r5IqenZtanPMaZtsF62YoudRHcedmpArTOxdyr7fVc7RWBpaLxkkR9fpNPkU8+o38s5S0u3VKB0bTVW/nh0kWLiX7o4JALkqVMHsaQ4+HI1wmgMfX973fnQEP5g5J7IIRo5/JrSWNFyVNW30WriqGVTVd00iB0yiSzZh47j6r0YsjE/YcssySwwXG5RAohK3IaGdQZ1JxoxDGdJ8pEzWKme+UFNphukBy1Pez4F8AEo/7rsk4LXvTZd/+VlPEQb9/8ggLZWNDoPwmZd8wT9AjqpBtCx0KUq5ksjQ0YQGaKlF8pRNzYfKR7hGcPCflpmhF2wm2S/gMOixf8BsegFJOvEzq9+5CvURUtwLZ8hVA/rq0MbH5GuOnG4sAwR/YBWsRpxo9UiZByjZYn0Pic7+g/CO9JPeXgRcIuhANSrXJGwaVfFN4Knh0OBa0fMl/flRPz1a3CV4T0UZBI0nS8SL6I6+FK7Ia8mxAJ56E58/N6+Umr6yWxaifxETsyDbi2DpH9EJ0h3FkGPqKKhUfLw=="

cert-manager-webhook-hetzner:
  groupName: acme.superk8.com

  certManager:
    namespace: cert-manager
    serviceAccountName: cert-manager

  image:
    repository: deyaeddin/cert-manager-webhook-hetzner
    tag: latest
    pullPolicy: IfNotPresent

  replicaCount: 1

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 443

  secretName:
    - hetzner-dns-secret
