---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aelabs-repo-secret
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  encryptedData:
    {{- range $key, $value := .Values.encAelabs }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
