apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: stg-elasticsearch
  namespace: elasticsearch
spec:
  version: 8.4.2
  nodeSets:
  - name: master
    count: 3
    config:
      node.roles: [ "master" ]
    podTemplate:
      spec:
        initContainers:
          - command:
              - sh
              - -c
              - sysctl -w vm.max_map_count=262144
            name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
        containers:
        - name: elasticsearch
          readinessProbe:
              exec:
                command:
                - bash
                - -c
                - /mnt/elastic-internal/scripts/readiness-probe-script.sh
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 12
              successThreshold: 1
              timeoutSeconds: 12
          env:
          - name: READINESS_PROBE_TIMEOUT
            value: "60"        
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: hcloud-volumes
  - name: data
    count: 3
    config:
      node.roles: [ "data" ]
    podTemplate:
      spec:
        initContainers:
          - command:
              - sh
              - -c
              - sysctl -w vm.max_map_count=262144
            name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
        containers:
        - name: elasticsearch
          readinessProbe:
              exec:
                command:
                - bash
                - -c
                - /mnt/elastic-internal/scripts/readiness-probe-script.sh
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 12
              successThreshold: 1
              timeoutSeconds: 12
          env:
          - name: READINESS_PROBE_TIMEOUT
            value: "60"        
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: hcloud-volumes
