apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: stg-kibana
  namespace: elasticsearch
spec:
  version: 8.4.2
  count: 1
  elasticsearchRef:
    name: stg-elasticsearch
    namespace: elasticsearch
  http:
    service:
      spec:
        type: LoadBalancer
      metadata:
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure

