prometheus-blackbox-exporter:
  config:
    modules:
      # module used for standard 2xx http ping
      http_2xx:
        http:
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          tls_config:
            insecure_skip_verify: true
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
          headers:
            Host: dex.stg.superk8s.de
        prober: http
        timeout: 5s
