prometheus-blackbox-exporter:
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 60s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
      http_backend:
        prober: http
        timeout: 60s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          fail_if_body_not_matches_regexp:
            - "true"
  serviceMonitor:
    enabled: true

    defaults:
      additionalMetricsRelabels: {}
      labels:
        release: kube-prometheus-stack
      interval: 60s
      scrapeTimeout: 60s
      module: http_2xx
    scheme: http
    tlsConfig: {}
    bearerTokenFile:

    targets:
      - name: aescan
        url: https://aescan.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: aescan-testnet
        url: https://aescan-testnet.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: dex-backend-mainnet
        url: https://dex-backend-mainnet.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: dex-backend-testnet
        url: https://dex-backend-testnet.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: dex
        url: https://dex.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: ga-multisig-backend-mainnet
        url: https://ga-multisig-backend-mainnet.stg.service.aepps.com/health
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: ga-multisig-backend-testnet
        url: https://ga-multisig-backend-testnet.stg.service.aepps.com/health
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: ga-multisig-ui
        url: https://ga-multisig-ui.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_backend
      - name: state-channel-demo-backend
        url: https://state-channel-demo-backend.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_backend
      - name: state-channel-demo
        url: https://state-channel-demo.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_backend
      #- name: superhero-backend-mainnet
        #url: https://superhero-backend.stg.service.aepps.com
        #interval: 60s
        #scrapeTimeout: 60s
        #module: http_backend
      #- name: superhero-backend-testnet
        #url: https://superhero-backend-testnet.stg.service.aepps.com
        #interval: 60s
        #scrapeTimeout: 60s
        #module: http_backend
      - name: superhero
        url: https://superhero.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_backend
      - name: superhero-wallet
        url: https://superhero-wallet.stg.service.aepps.com
        interval: 60s
        scrapeTimeout: 60s
        module: http_backend

    relabelings:
      # This is the part where, the original SM endpoints passed as parameters to blackbox exporter.
      # More info: https://prometheus.io/docs/guides/multi-target-exporter/#prometheus-config
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: __address__
        replacement: prometheus-blackbox-exporter.monitoring.svc.superhero-prd:9115
