prometheus-blackbox-exporter:
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 60s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
      http_backend:
        prober: http
        timeout: 60s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          fail_if_body_not_matches_regexp:
            - "true"
  serviceMonitor:
    enabled: false

    defaults:
      additionalMetricsRelabels: {}
      labels:
        release: kube-prometheus-stack
      interval: 60s
      scrapeTimeout: 60s
      module: http_2xx
    scheme: http
    tlsConfig: {}
    bearerTokenFile:
