prometheus-blackbox-exporter:
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 60s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
      http_backend:
        prober: http
        timeout: 60s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          fail_if_body_not_matches_regexp:
            - "true"
  serviceMonitor:
    enabled: true

    defaults:
      additionalMetricsRelabels: {}
      labels:
        release: kube-prometheus-stack
      interval: 60s
      scrapeTimeout: 60s
      module: http_2xx
    scheme: http
    tlsConfig: {}
    bearerTokenFile:

    targets:
      - name: dex
        url: https://dex.dev.superk8s.de
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: base
        url: https://base.dev.superk8s.de
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: faucet
        url: https://faucet.dev.superk8s.de
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: aerepl-http
        url: https://repl.dev.superk8s.de
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: aesophia
        url: https://compiler.dev.superk8s.de/version
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: explorer
        url: https://explorer.dev.superk8s.de
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: superhero-ui
        url: https://superhero.dev.superk8s.de
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: superhero-wallet
        url: https://superhero-wallet.dev.superk8s.de
        interval: 60s
        scrapeTimeout: 60s
        module: http_2xx
      - name: superhero-backend
        url: https://superhero-backend.dev.superk8s.de/health/backend
        interval: 60s
        scrapeTimeout: 60s
        module: http_backend

    relabelings:
      # This is the part where, the original SM endpoints passed as parameters to blackbox exporter.
      # More info: https://prometheus.io/docs/guides/multi-target-exporter/#prometheus-config
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - targetLabel: __address__
        replacement: prometheus-blackbox-exporter.monitoring.svc.superhero-dev:9115
