apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller

version: 18.0.0

dependencies:
  - name: traefik
    version: 18.0.0
    repository: https://helm.traefik.io/traefik
