apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller

version: 27.0.2

dependencies:
  - name: traefik
    version: 27.0.2
    repository: https://helm.traefik.io/traefik
