defaultCertificateDomains:
  - "*.prd.service.aepps.com"

logs:
  access:
    enabled: true
service:
  type: LoadBalancer
  annotations:
    load-balancer.hetzner.cloud/name: "traefik-lb"
    load-balancer.hetzner.cloud/location: "nbg1"
    load-balancer.hetzner.cloud/type: "lb11"
    load-balancer.hetzner.cloud/use-private-ip: "false"
    load-balancer.hetzner.cloud/ipv6-disabled: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
    load-balancer.hetzner.cloud/protocol: "tcp"
    load-balancer.hetzner.cloud/hostname: "prd.service.aepps.com"
ports:
  web:
    redirectTo: websecure
