traefik:
  globalArguments: []
  additionalArguments:
    #- "--entrypoints.web.http.redirections.entrypoint.to=:443"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    #- '--serversTransport.insecureSkipVerify=true'
  logs:
  # Traefik logs concern everything that happens to Traefik itself (startup, configuration, events, shutdown, and so on).
    general:
    # By default, the logs use a text format (common), but you can
    # also ask for the json format in the format option
    # format: json
    # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      level: INFO
    access:
    # To enable access logs
      enabled: true
    debug:
    # To enable access logs
      enabled: true
  serviceAccount:
    create: true
  service:
    enabled: true
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/name: "traefik-lb"
      load-balancer.hetzner.cloud/location: "nbg1"
      load-balancer.hetzner.cloud/type: "lb11"
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/ipv6-disabled: "true"
      load-balancer.hetzner.cloud/disable-private-ingress: "true"
      load-balancer.hetzner.cloud/protocol: "tcp"
      load-balancer.hetzner.cloud/http-certificates: "dev.superk8s.de"
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
