defaultCertificateDmains:
  - "*.stg.service.aepps.com"

traefik:
  globalArguments: []
  additionalArguments:
    - "--entrypoints.web.http.redirections.entrypoint.to=:443"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  logs:
    general:
      level: DEBUG
    access:
      enabled: true
  serviceAccount:
    create: true
  ports:
    websecure:
      tls:
        enabled: true
  tlsStore:
    default:
      defaultCertificate:
        secretName: traefik-default-cert
  service:
    enabled: true
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/name: "traefik-lb"
      load-balancer.hetzner.cloud/location: "nbg1"
      load-balancer.hetzner.cloud/type: "lb11"
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/ipv6-disabled: "true"
      load-balancer.hetzner.cloud/disable-private-ingress: "true"
      load-balancer.hetzner.cloud/protocol: "tcp"
      load-balancer.hetzner.cloud/hostname: "stg.service.aepps.com"
