---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "rabbitmq-secret"
  namespace: rabbitmq
spec:
  encryptedData:
    {{- range $key, $value := .Values.encValues }}
    {{ $key }}: {{ $value }}
    {{- end }}
