apiVersion: v2
name: hcloud-cloud-controller-manager
description: Hetzner cloud csi driver

version: 3.1.1

dependencies:
  - name: hcloud-cloud-controller-manager
    version: 3.1.1
    repository: https://helm-charts.mlohr.com/


