encValues:
  hcloudApiToken: "AgBs/et9IG5dGWYynPnw4/JEeobm4CLPzVX8u8Rt5Bp6I97UfCAD4elVhWbHiLUneoOwVV7B1BjAF7CGAWZynzavhJSAIvLyncdZbv03d4iIogkfuVulWPEdXugu8Ab3D1sn9Q4U6T7BNToHn3dxzkc2OnkWw2p8dmKYwVmb4znmwzWHMWrDnvCnxzC84HO0Df/UKYNDQhJIvDmL1uNFygsnOuZaQ/8ejNrtM/FulqgcyOLPevtlOAj/eAkCVXPT+vr/Z4ztEDlLfMtff+UkBz5hofs8FQO5oTrnHNyZ2lEch4H7nA/zrAerIhPEaPaIMD4qjOYFnVpDVBpKtXqKUooXedQGht2yHNnRd2hCObUyks+BhmohNPO+IVioCFQknm7Efu5zd2GDQdiP+M2GHNgfxfQAB4/iSZRxkTdmNXzdLWdJEsGeX1PjY14M3K698gRlemBReRfP3IUMIpKi17fnBWFb2JRN4U/eH77CUosnbPmT2gmB19mm7fbG8kiOkdJzEa8V/FOg1s+2wdUkasU3qBVyGuRHDGZ5btWLFV4j4I+oAGsM0aM0Vi9qkEACEEC4h3g0DEqG5HiGkuecWnqIuulzPIxKYO+gXKqkcAv70egoTLwIjX32EfH4u9UtxG4BnDmIUP8XbOx+OnTy90bVVJck43y+FyvcINP6C+4DAMCIHTRuE5R0aZw//6zN1pLOG28UJkxDG26LytX9c3OQJeQHCjmIqNIRTRmPAq3edGpk45smG6DsLqp/i8LJqcH7CEHjN3GDyNE5ZV05BILZ"
hcloud-cloud-controller-manager:
  env:
    HCLOUD_TOKEN:
      valueFrom:
        secretKeyRef:
          name: hcloud-cloud-controller-manager-secret
          key: hcloudApiToken


