
apiVersion: v2
name: argo-cd
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool for Kubernetes.
version: 6.0.0

dependencies:
  - name: argo-cd
    version: 6.0.0
    repository: https://argoproj.github.io/argo-helm
