encValues:
  dex.github.clientID: "AgCkHRMzDm8vDdwcnn2DGMcHCswq1us/xf2jYg4CN5E/tKsyvcpX3e2l6qGn5ykjo3kZ113+g/zFSapdL3McI2hTgYpnrW83t21gbIPb2daLlT8DuDPaWQ8UGW/xrbLTYrFh4ouDzpYt4DtwZj/90odJjZrK6ei0PEhUkF7eC7gWZ0iOrCB2xuIgauvb9LKF/bn2Gm7Q9L93qPtXMlAWdlANtDGnTWtQZXEreUSLLgBTeFJwMcVKMVUKRIGt25MNAscIXyojD54ft6XnPCDqpkqP0AAkVvbEmTYJtoHjXacAbFX3ybCa3aKACZRkMCMrWuabL55xUmWgGp8kqien/sDcz4TdLP2mPLvq3BlDddU9G8UzBkLqc22vJrKUOlC1k+AuiJwuzSNssCYaZ/2+kTtdkm0Dz0Sw+9AbcckUlOBUc2hHP5JhA8QSTKiPIjiszAv8/Ev90oXGcIqOBzf56yrLJ8bpZ5ljvQcH/oHosMKZK+TtG4bPDkV/C9aVdiLpzsJ317tBdDlQK9CJQ6jAFystUn2oFjx5agURkkDsCAxUeA3D9ly0DiDL7y/XP/SjTsNWRy236Oo4b0vpciuO/gY3no7ZEY4PtFmEae+Paz2NdmbpCx5y2eNO7J3xS5vq06JDQ9yzilw1DTlAAtaN6z+JTZ+8f1KGMiTge1Ngr7EaswJirvx1vb+HUniTkEkXQ3/20PGZzo1l7vT0LdZCdRV6ITDXEw=="
  dex.github.clientSecret: "AgAHRDyzI1/S1mcAV/TrZqaMSEppjph9oLZHqj0/ih5Bbd9a1l+vK92hg+NtvGvJUyP0ZosNldaOVRIbBBgM39t/tIHI52ASZFQOxfBQyXu6vDuocygGYrpZfxZVMQG5MQpORdtxGswI2fwzogvmyLmYxb/yScvi9ugdNJsUIGQ1/UwwGa3b0L/Ll6eGcR3SrzGvIdpugJZoez6dQEghvyoldR2pCfAD7PxDZuH1pTTQzHInkRu1yVu7AjGkh9Y3Ff6k5DsbAQgAuPFPzESKVz9alTwmPhctNMd1Pqpi4JnAX5Z2+gMBXPq/6H0zdmDxzN22+EEskMp0AoJwworNu4J7BZg9Y/WHGNxckuJmwT5z/JlMT5lzIpxkz7wFIZLvXDa9FJk+xeQPuGd0mvt9VqBpBp8kuHb/gTH+N3SYjAhyCguhv/hMvLk5w7d50tKCi1w1d13Hzt0fvxV+ozGI6rM0bcVHifd3VHF4jTrLkqjGcXnBbiXJW3UnbP3KREVgwJUph8AUulwLIJ3mSdSApvtIUrTpEb6y4mVIy+5F5VV3p3GCb+6LnlK9mO+eEXwJM8WROXPZ3TGrpTwvXsXVY2s7XHhRmyRbIxnHahA/1sHo70ODG+HOxMVE78MS83+KcawtqDByzeCQ/VQ6ONoAm09C1RTdK2qtzzRVLnwsoT7f33UYzT87bCT8dpjMIJWVXPdD55fEuZOb/iNDkb2JV9i2KPVA43Bcs71azS96E+Nr6v8Ini2Q7zJP"
  server.secretkey: "AgCTX4Gf9XciR4gkmAH2WL53IKNQ1eESiImeQFue0LsSTE1IhTJGQqlkjRvF0VddD8U5Ctksf5gkksF28xeKzMkFaIXZh7QgUOs6melZuP9xTXNOYOMwBj93vi0Udj4po4SydIkkW8dYNKkRwR410x3AsA0SJ5G2QdnrRxy3s6iZ2fx/+hnU5ZSAfUPJ0vpQYsJW+q7HeYwBhlGpOZYZoIFbfkokCkKp5iSW4xPQMaL9zikRzRNZv/gjAk4V+eWRui771WoQRv9LHfrIbnvtB+Vv000pMH/J8H0VEPlQMp7KnQFK74FegH24Cv7jR4VRdcI4Q1fHnvc+hW89Q9wE91m97PfzvzfxEVDs3jr4Oy/qtkgyXJCKnX2EEy7bWaV087NJXtvwr7xEyUouSZlu2JNfWIdBS0r06uvPn9n7ERlVV9kYXT2hmcc+zBsXJYMGjx/3Jv39vDmropYC8safUrNX4PiWqMjT4+eOnp0CRL/q3ANMDuS5G4MfrdnMg/GSjTZqhWHhEjgHdcio+bdbiddWrkfp6yMgpEX6Z3VDlVwPbZcc5ag6hP1DmgDjsFIqajBYhvhT6sxtziwj4Hnz+cZMeHdasjQGuXDmQ3XAOFCyydaEGrAHel9l9oMmIIZ7Ae/RC3LbGwNETilL644QZdB7e+dWaiHFDYI5h1zdDDDtKBQ11ciBW3GXOhlEiTGrFSEbUiTno4ksFGWEV4Um2PYC"

encAelabs:
  password: "AgBWzBzizQrk4CjxAaDw+VuviWVvCGk4llhE3rKFjE8vAC8oRQyfv+NEBXDHPo5OdgQqXxWR3fNdvQYsbsNWPN2Ly+yuoW8o6Qc1EOqoGFU8VWyND+CSZTF0ffxrxrcGNLOgxE2Em+8/LP8Gt60Y5aCJJuH/Yv6GvYh2KTttd84kzaVaDoxsc73vjUM5/z8zgJGKISlHqplg10KKjuEi7Muoh4Y4O96SI670YfH1jY7IIKopxVmT+rn2haFJcF9aapN2nMLIXV9rbzCkkVTRbwmKdnxMoYWMzkz3Uswy9ZjFPTQLoeQhdv3FNNeFnCbDaapVNY305bQbpp3NyaAs9xt7bM+Wbfv3Z+U9a0n3/XBA40BHEajtAj24PQVq6acCACaV0zLEZ7MmWD7HEKtgzba5H6sWABGeXS/TQBkfCpYkUlVb1HNfslTlmMoVgktWe/wMAnGZ0XsuGgWAr77Ex83jrdTk0sGXjpe7YDylR//POxHnsramqx3UNBsZ3x+3238DbKvp9sUituGQDQBmpEAgDa4upyzxXkk74JI0KeoEgxsZjIzj8r68ZRvC6SzWAJw1gDedVd7AywTjPjWBDXWr8pybFcaA0zGW60FJvYBHLhoHMsDhO4ZXXmJ7ExUSkPBof/eUx3Ef5urPJqLLL0VMchvOqwqRY6ZzIzsnvv8Rhv57F4kS/F53gKr1tKko6dP3GivlWqHNRTGRKI0qE7sIYL6Jb41LXP3JFTYbhfj2o9H0bxPrBAKd"
  url: "AgB391Gj4H11P1OiIRxR9S/IF1b9SyJO8669foM66/9rtm5FVZmdg/ij+h8GR/NWFZWB4dPI8OWGC6CBeLi67SJOEuTmGRS32iLC3nfAP/L5b/iD9oJV2UJ9Mo9zsXzX/zG66klfVZVYv3DOGlwJextO//Iz8F6s0kTgcc/5MhIDaU5LMm3EEXqotZiEM/ewaJqC150/U6FXNberj9hqrUCDvV9M6VcUUY6fTiqq+hynSsKEESsFTY+SllaJZvfkXdhLZrMAwaVemOdHtjwyDoeZEmblf1Mu6cgmWQ0IdqSmORYKa8IQYoF0m2R/Xn2Xw5laSBxqhK55KhHYMFq2AVU+XVUHCC3Qw9LszytKKq0/uX1txB3F8zvGfG92c1Ku13AbxxKnw9W+9ZgBuguYHYpt+7E3/p+63cEfIVAFSpAOgQzv6wy8AUfGEYw3qU/l3Izf6iGBkv5kcNZbk7YRZXhNjYDQmue8zAPfUcHpACmASXMuRmI0biL3q9m9T2Kh/3nPmh5IaQVy7mgqnXfbgbiUuyNrNfx8AEEmdgk/cKfRtrgzK/zf2eBVx7G4xA4MHDoZ8TQ0IkvN04EUmiCbPXiE4HQ8XJ1p3WZYSGevOLgmoOyOEVb4m6wTVwnD7IsIOCIxSN5lIfVIRA/oW7lGak9udXpkd5b+JEMKHnI1rR7ftWt1x991hPld5WsfVD5bK7U4x2SVkTj972fkifc0ecR8Xxz1tzHZRqjn5VsVGXLmCgnABdJ+2PsSnFILAAPENdk06MQ="
  username: "AgBBTsv3TkxyDtMIZY6FSil80bV9jMqz6Gm8jSr2m4wfljj8Lqxu9F+oFaWlwpVwYqgEKjA1aMT0t2O/f7NepqdPKxQWmgtH1MYUrKLQQ920KfrJ9FUzlXz0ArVC7OwtuJRDpWRsHkgN/2bvPq6R7y7MibW1o6xOZdrHxshlpRTsVdUZ56pTxGx80lm0bmPdkzgvC817nFegEokCEQyTNHDOH1YKI+E6M06+tOpqH2W/DgrwJVowfzG7UMLDMyonjY5doTPl3ANQchUW3OUQ4qeiWgBmPPJcYn9/uokRSr76XuVP1fH8e9XjSsGwKxA5BWzYVf/1mU5AIIYd9giFy1aH72/VpmI6FzK452oUgb5d9oQpiqG7U3pgz1f/jBazcoTZmRkkx5mry+I7Bw0ifG3KiLMXsX8iVT9euw5fdYzyjOs4b+7bkybqfjpqcKeH9xQUPZULRubFQdKbd1VCAWWPN3FoBE0adqappPbsxs2N7ScfqIAz8jvmOCs5MhEdbT+BvAN4mx1I0FaNP0e4XwKP++FuBLbyX5XGs0z7BADKwY4TleF0cxGxtI4MS/ozDQjuSx5IpvQ0PnIeWtT+YbaT7bhd5AC+vUJqLMU4jBG3beFAAAnb1gk181vYlsoGvCW7Nh9Wd9gd1nK5WCbw+nnrBg0ktpMp0jEphVLWm61ae5HKwHpyAw0Wj+f8HM1l1Xu88c21o6QI6g=="

argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      pathType: ImplementationSpecific
      hosts:
        - "argocd.prd.service.aepps.com"
    extraArgs:
      - --insecure=true
      - --repo-server-timeout-seconds=180
    config:
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      # url: https://argocd.example.com
      # Argo CD instance label key
      url: https://argocd.prd.service.aepps.com
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools-superhero.git
        - url: https://github.com/aeternity/gitops-apps-aelabs.git
        - url: https://github.com/aeternity/gitops-apps-aelabs.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
        - type: helm
          url: https://helm.traefik.io/traefik
          name: traefik
        - type: helm
          url: https://fluent.github.io/helm-charts
          name: fluent
        - type: helm
          url: https://charts.jetstack.io
          name: cert-manager
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: aeternity
      resource.customizations: |
          networking.k8s.io/Ingress:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs
          admissionregistration.k8s.io/MutatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/failurePolicy
          admissionregistration.k8s.io/ValidatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/failurePolicy
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, aeternity:devops, role:admin
    additionalProjects:
      - name: tools
        namespace: argocd 
        additionalLabels: {}
        additionalAnnotations: {}
        description: Tools used to run the environment
        sourceRepos:
          - 'https://github.com/aeternity/gitops-tools-superhero.git'
        destinations:
          - namespace: tools
            server: https://kubernetes.default.svc
          - namespace: argocd
            server: https://kubernetes.default.svc
          - namespace: sealed-secrets
            server: https://kubernetes.default.svc
          - namespace: traefik
            server: https://kubernetes.default.svc
          - namespace: kube-system
            server: https://kubernetes.default.svc
          - namespace: monitoring
            server: https://kubernetes.default.svc
          - namespace: logging
            server: https://kubernetes.default.svc
          - namespace: cert-manager
            server: https://kubernetes.default.svc
          - namespace: rabbitmq
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'
      - name: apps
        namespace: argocd
        additionalLabels: {}
        additionalAnnotations: {}
        description: Applications deployed on K8S
        sourceRepos:
          - 'https://github.com/aeternity/gitops-apps-aelabs.git'
          -  'https://github.com/aeternity/gitops-apps-aelabs.git'
        destinations:
          - namespace: apps
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: '*'
            kind: '*'

defaultRepoUrl: 'https://github.com/aeternity/gitops-tools-superhero.git'
defaultTargetRevision: prd

applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
  traefik:
    project: tools
    namespace: traefik
  metrics-server:
    project: tools
    namespace: kube-system
  kube-prometheus-stack:
    project: tools
    namespace: monitoring
  prometheus-blackbox-exporter:
    project: tools
    namespace: monitoring
  hcloud-csi-driver:
    project: tools
    namespace: kube-system
  cert-manager:
    project: tools
    namespace: cert-manager
  rabbitmq:
    project: tools
    namespace: rabbitmq
  aescan:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  aescan-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  state-channel-demo-frontend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  state-channel-demo-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-wallet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-gateway-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-worker-tesnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-gateway:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-worker:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
