encValues:
    dex.github.clientID: AgBumoWs0TK7AXijGpA6SZD+kbKsgTTSTLLgywZ/9AV9fRa5uS4+Iyj05bC91K9dBZiiEdfVYElceS2UDjm4VVADUNsM/u1DjAL10YsiA2gGmz+BAUvHGs9xoEECwJ2VoxsS3VzaewxUTVYdI/XCTAlo9n7B3AGo/EnKIoqaiSzo5SBf0Xb2p48ZwhxugYtQJl5PeCA9Msi0SQYRTKx+oJzdeKjCxyPXmKdNOVHMckptiHrOjqFWRfBIcMZ1ecULuxU2kPRdiYyZsUE4qlfCi7I1epFc8auNIzhFzP3YzgXu2K41wwr4s9JW9tM2HimJJNWSG833v6ofxz2oCYD04+DGehOf0hFuyXaq5wIG+RupSb2dWcobmPLVCxGhXs66KOrxUpEkHFq6srfIuhjC7Z2lt493HcxJygzNO0YFGhq9ity9iw2nfRGDEPGPj6rIRZJu9zWSj4AcXwfLa/oP8WR00zyNVqCKrpYTUXrQ4dies5MCFBQ1kooCuavRDz7qflJxuUnEEtauRi0V77KBbWa81ZpHv3jiCil03CIzr5UP/aUcmuYjAqx7QSmZmeMfmyaTk50ssOxLYdR1apYOalNNiK/FAXxEy6obLidYH0WloERlgHp0lEMITbaN7Xvu9f8UUr16+NhK7iuqJSWLBPF9dC3eIpCWi8UkR9AY/EcxL7bkMyBTnj2WJm5M/WisnhlwiNU8JrYwVh4mKU4BETVnlh4nWg==
    dex.github.clientSecret: AgCph39t/oq7+bIIzUNF8cjT4m51NuWJJY5z/UMTnOdI4LqRrdnNcTGYJkz5qlBmiEo0+HVp3VTDOkp3QCLUjwMoEYNPL/sE/5vdKEuPgfUFRNEuUrJrEf3IDgE8Zy7C3wxb5kzv56pQeEgBtxU2uzmltHWRnqShy2xF3KQxUI7/L24bHNW5v1uysILr8C/vGyf2npHThQ20T7uHu1+EOlGI2AWNOBsEKi95pe5JkGU+4pBomunN9QT5ibr528KMBulLJOhw5ZXx9lYGRwWFEDeUbxb3vdtP7xreAR3KZaXIYrOm/iWbqCROGoaW+qtZ6owMKBSGrMrVMmYk49gFqa2mg/dU8/nnFAsMA+x1d0HGd5uVvA5sDNncAL7D5X11h5nVYNaM6sub8lqc3fawR6l/V9ExiFigYwZEyv4d/YLNuq0OBJIzqbUbCA4cL9ohwa8oIQ9Lw2M4U+W+zt7O1HARZ6pTuYy6RFaBCnAX7KAGH7m4pMjOdhqUPELjyLrOO74DP+FIjpvdowQ7NvMQkUV+8p53gQxTDjrKnm3NXOBRn4hIufzTyL7ViDb/0tPKFr/t3ByTxpsky3leIyLiM7gp9nzKn+6GOVY8NFUnpkToEtGvB0fpY/1J21WI6Ry5+4O1Qb1iW++Vn1OfR21U9JnEG0ITlRw/I88rN19RXF3gRFkKts5ApGXDrLM8vqfVchySiSvQgUAO67z/ZYnCLdcukkNUtQcE/lTWY55tXNA4guLnSOJD2oEM
    server.secretkey: AgC8sdkh5cMmZu6+O8LQV1Z4PANQsQRrn+V+25KzC+9MW3Sma8BIGvwa6yvpAUk5dOy7gPM+A9F2QzToJd+sFmgv6sqgw6iiyCQEI6k1BswhYVYpk5BVk50Fij4FJto7SUSGTdpxpb/PTxFZET6ocartwDyqce47MdFMlKm/Tck+y9TxoIoue8uVcI3X8gNHgTHl4D5BkMG8bjsyWjzpQ5klnRoMhP7U3fHp1fGIBL6wUc8/EBk0iFiMe4coyvGqdUKwwSXje/K5CR2LlWllvlte4atBA1tahu/NehLAHMkvSiMtagGMonIGH748lS6mD0Tg1mvSTQEBL4X9pbiQwOBELSzmHAcy9ldh2LT6rFXS4jhzeclhrqzcfimxkggaDyWISee1CRz5nM6vfdBWhL1VuxnIi2E6Yg9mlYBlptzE37fVFl9zwxPCMFHIYK613dG8jaRVj6DI6ixVKMKDd3FAWaZgTes7fTM/LTqgjRHVHqqY4ULy3py1UIsByp5Ecd6aU3WBVTx5pVZqV1qN+TDc3VJhOM4qQaM2wwXSxhDBw11rIfsxlGvuyt/+JZAKhT5AOFyM0dpz7n30cMLSbU3NUmbMn/nzLN0J0j0ebTgylqAwxr9ob9q0TNxzqTdEnJYX49o+hXxsHYL8kC4j1b6PLv8C2ItBEUyWOQ4TZBAX7pe5Rq+Wt3ezFUHgFz5Pikewep8YhX8ZR8ER7I/GzvjNUSGh9D9Djw2NTy8xFp9pog==

encAelabs:
    password: AgBE2+NZBJWQSGez0gdvnmdg1zQ5uHLXbvM6ORrGr/C1WnuLM0qP9Zel7VionmLH7ufTlWStJi7cku6EHnnyKmEIHfaT5ATCE+HcNZloXw0LoqHh0Rh0UpK79pZFfOH/F/UFtH+0lnHsJ6xj8cDhbn4oKLSfvH1IUOKrA/mFGOl6duSgZkj4p9Av3Vsq6vKzhVmeUkU36bTMe3giNiTEnAO6cYsFIXCH3N2md8iG9GB4CDOeSEtT7MEIc0WHgjF+IA5QNGnqVKP4l7++t9JIe+BvXmWSRakg5O5bVZGimjTx6JBkUr2kqMfa3dGxU4QU92Shn8xYVK5NRluay7znXoD3enyIfEub+kU1EM3HVJkjRzjvDkySvu7pmCEXILBSmlIKJZrxEwnC9tI5j3nMJklbUOjqv0g+90Z3Xy8JK7hvIal6zJLF0fyQn/tlu0amExm3EjN/pSzFXbMNZEmQRAD5aeimKBo9yk3mXhikj40f6IZKBDtT22xefwT3lVMZY1PnGcJxlhPAbNoowTFvqJsYumiu4XUOzz0hlsdOLgZOH+wPZtfQcN5Q07JaIW+UU2foLxRAohU5Cd5qmZZd7Lnub9fy4Zb9pXhZN5HUwHBkQJ2FaqKDdAprcRCk0d0UVgyA3TVMlervJytwwVrPaPwA9ONjPZpd6LDhq8H75vrLpG7xZg9pK6mzjubyuVwhDZU3BpTWqdbVWxMzIXqO7cOtyz1UzuSMZHpvyzZ+iFRq8C2oteRBkZ5s
    url: AgCyR4r/NtQ/jQT6gV3wq8iHmZg+NSrndrupbk/5DMVJ02NUf/oGiGYtwfJpc7eMYu2K9efZWN+IIGvKYSkf0GkimX5T6Oci6rPc7i7FkToT3JFqrqDsWzHqOMQjCn3m/c3eMRAJVJC59GDF0VqkCIusDVxZ86TBDAuw++j35rnD9hwAp3SYehIkKWktuoQSsLzcGBbQkUV0AcVx3n3fN+cwpgQYwASd7UOtKjNaQpmX4VsEIGPtoX+fuPDziGb8oOBg2ycsML85NiMpVJDNM9LHalw5uXvwjJkVR7XxxE4v5rvUeFloHcTVc9oVcYGAQvgGZeF2Dg0E1yTNVQp3fHPKCQHu41NJfKLkyzeHrqEXER03dJ/9gQYPpEY2sBZ90odxBAabI+iX3drsPZVip1xVtN2Y+vPna7g0qJT6li1KvSHqjRlpl+kWfZ2/CGUBCKQg8Zq8IKU9mZIBufKCwQGECteXI1qm9zU3Bm5LKEbCASUOoK91iKQxwQ/dEhq5fg16zjunzdqn/Dlau3WBCTPHDsiI/qhFtFeCyENgVGEdN4DcQ8zDcaoNpIuQWRK0wSntqgAp+9t8ZCJWIfG3p/0jfjycfEEM5iwgTS7oAxzqICeLX3Hqh2lUxAw9FkxsNKGml+ri4FuaFmVqLN9IgtUhQP8dUojtOgnmYFQHXfE38yscv0D/xEuDQTGfXidgisooYBy7xouoTlKURncdje5dvc3gTxOgfgqWy1rHWCBqnQSb1T5cLAIXuG/j9deKzs0=
    username: AgBGLxL1mEEThn1ZZMJtslg/G+g3hfgdfqakx5bSpkmISaioCr6QrfoHFpScCY36D9ez9EsPY58Twrymq0LY5K8HsF6SHQfjJNj3R/UhcInR6sYKo5uDa6H+/NPLT1EFS8de/RXvTf+8H57DH8mXGED0a3HQeX0epdDt7NzkNZoiLXHnL6IBq61RYg5zMbE2rZBlnpLRnqLe2pEgumT6RwU2c1mUiBkqHo/RkIeOTn3UU8fSOlF8XFUKpymLDLD8BO5TOZJR446e/L/g9u63fefmYCayDa/pjeY/h8/84dxJyCOwhGBVfCnmkiM8svoJ/pQm/WaW46amU6dl9jJV50PvbjLvy7Md734IkziFfeO1C16SZJDWMfDduDWgY5YG5EVlghro1sburqwxCtKpXvWpUU2xDo6G/dRL/IbXjgUBduW7TEXF51KQTRsCZGj/Ctw2HnfCppfOlHl0lsU3CzSaJb2s6QzvF0N8eM87HRRdhtKVhSIahBSqV0laUpt6pNqhtELD8GhyRljrLFeADJmdVb0hBLxLE0nXg/QPoHuhsMgWe9RPDzg7+tFNEUOOhEpgBjRuMMKLqq8UtOR3l/gvhWxfUmZ2NSuwa2GSmwQPm/BAYE2v73SDzjuLRH4qp4I2tIX2AOOd2lRSuWoOHWZhx5O7ClBtpLwNF67yi6ORTUzW3oZXmbv3jIHYqnvVWxyXqSj6W6z5GRzDTIb0NQ==

argo-cd:
  global:
    domain: argocd.prd.service.aepps.com
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      pathType: ImplementationSpecific
      hosts:
        - "argocd.prd.service.aepps.com"
      tls:
        - secretName: traefik-default-cert
          hosts:
            - argocd.prd.service.aepps.com

  configs:
    params:
      server.insecure: true
      applicationsetcontroller.policy: create-update
    cm:
      url: https://argocd.prd.service.aepps.com
      users.anonymous.enabled: "false"
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
                - name: aeternity
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      # url: https://argocd.example.com
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools-superhero.git
        - url: https://github.com/aeternity/gitops-apps-aelabs.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
        - type: helm
          url: https://helm.traefik.io/traefik
          name: traefik
        - type: helm
          url: https://fluent.github.io/helm-charts
          name: fluent
        - type: helm
          url: https://charts.jetstack.io
          name: cert-manager
        - type: helm
          url: https://zekker6.github.io/helm-charts/
          name: plausible
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
        bitnami.com/SealedSecret:
          health.lua: |
            hs = {}
            if obj.status ~= nil and obj.status.conditions ~= nil then
              for _, c in ipairs(obj.status.conditions) do
                if c.type == "Synced" and c.status == "True" then
                  hs.status = "Healthy"
                  hs.message = c.message
                  return hs
                end
              end
            end
            hs.status = "Progressing"
            hs.message = "Waiting for SealedSecret to be unsealed"
            return hs
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, aeternity:devops, role:admin
        
projects:
  - name: tools
    namespace: argocd 
    additionalLabels: {}
    additionalAnnotations: {}
    description: Tools used to run the environment
    sourceRepos:
      - 'https://github.com/aeternity/gitops-tools-superhero.git'
    destinations:
      - namespace: tools
        server: https://kubernetes.default.svc
      - namespace: argocd
        server: https://kubernetes.default.svc
      - namespace: sealed-secrets
        server: https://kubernetes.default.svc
      - namespace: traefik
        server: https://kubernetes.default.svc
      - namespace: kube-system
        server: https://kubernetes.default.svc
      - namespace: monitoring
        server: https://kubernetes.default.svc
      - namespace: logging
        server: https://kubernetes.default.svc
      - namespace: cert-manager
        server: https://kubernetes.default.svc
      - namespace: rabbitmq
        server: https://kubernetes.default.svc
      - namespace: redis
        server: https://kubernetes.default.svc
      - namespace: plausible
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: apps
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Applications deployed on K8S
    sourceRepos:
      - 'https://github.com/aeternity/gitops-apps-aelabs.git'
    destinations:
      - namespace: apps
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'

defaultRepoUrl: 'https://github.com/aeternity/gitops-tools-superhero.git'
defaultTargetRevision: prd

applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
  traefik:
    project: tools
    namespace: traefik
  metrics-server:
    project: tools
    namespace: kube-system
  kube-prometheus-stack:
    project: tools
    namespace: monitoring
  prometheus-blackbox-exporter:
    project: tools
    namespace: monitoring
  hcloud-csi-driver:
    project: tools
    namespace: kube-system
  cert-manager:
    project: tools
    namespace: cert-manager
  rabbitmq:
    project: tools
    namespace: rabbitmq
  redis:
    project: tools
    namespace: redis
  plausible:
    project: tools
    namespace: plausible
  aescan:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  aescan-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  state-channel-demo-frontend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  state-channel-demo-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-wallet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-gateway-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-worker-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-gateway:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-worker:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  governance-server-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  aepp-governance:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
