encValues:
  dex.github.clientID: AgBGzfrDhXZUb1Gvf+TMvXUMad47bS2iVKoc7YN9txqzMcV8UZ+yczaTqd76ZLYRbozuwdQ2gKikw4tjKIn979Mo6DgEWF9+rizN1HIeHJzJWzcgORdY0U7Pjq4//MQYXuwuBVp2Pe5w8UsQ9F+hgN/UP2M9WiTQZuysYiLIKtIII/LciEcMuFiKnuei14jSD3t7e9K/eKq+qeIGHeQxsnkPL5Tm/BYYJnO1NvK0W6VuK0SG+ynhfisEAeCxW+nxhx/smZDAQSRVYLgE0Rbb2xw+esQPdJKo50SNnt21xGt6xkNHirvHXngRN8Exob6J2E1XK1dq+7cBGBNCRy0SO7DjtxFH1FX8qpuHMXHe8IV41wiVQV9zJuAFeC2FmSdCKavoSDcxs+spyZXk4xOjQE0GrheZ9pWeDAPOmm95g29aRHiWZenfeShQVV0tvLDPlTCwJ0Cnd0YpD34AOIbJUNvNnyUd8OujpBhdX5Qc6RasV3MXvOTjkH/YPrlFd3YxwgY3IgxCLPqn4Un/ZNbRDcF8JmCf/uP97K+jm55MOVZXy42X3FyI5xRvZ7/zxseLmfuzd4Zbb6+sDaXV4H6M8/R7jv3nAsNM+vhCIUrZJN67fjjQNIOuQCumTh2zqFNJEUv2fJcTEjxWuyqLln9jwpJLWgrTWdEO1JP37gJ719NjAcKkAhskQjZfzl1/kUM/oF6HUkIALXV3f79M7Jr7xpvjje5ulg==
  dex.github.clientSecret: AgBMYbYViUfY+uEtTlkFHm30hzkAWil3RxzDiDjTR8mqh1acfZCzZHYaufBE+vgtSp19YgwQdmlYlish9aAu/1LXVsjKY0bE9QMMK1CjbZwX6yvkmR6zzxFmUO+H5huciTIicYgeQDHCuLTrvNoxtxlNgxsGDbxVgrDe/anePZRcUoqK//wCOZZPdcfum5TcE46vLnIhq8c09OYDSwDGJi3lsP+0Ilb6wyiOPb+IWLBXugjePcjyc4ByPj1fynpt7Q9w8AAYivbuxQo+rCM5oIDa2NzyVUEUbg7tftUHNveAhH70XlyA00T9gN/SGD7ogaxh5a4ejM1zkQxCh+ZBdXb3P1HCTxYuCGhXN6NdABionKW7/B22WVDnOkD1o1/0JKpXV+k0pNbf3Z5LfSHikqP+N+hXVuhfoUSuSWO+hcwxgLumLrrIBsM6QUg5Gt/4soAa9SOQSBRkrDl5q1aVBaS0PJBe8l2vJTaYlMnEquopFp4ukMmyNJN1kcgzTz+WT6MDbRAcRnLhWlyEXTtOXYlIQTl7GmwdZRHzajHYTk6Kq5OYnSkyyEeEI9BeZNxQqE/GNhafXI5s2nz7G5pV75J+8EXWOYMBGeBczkDnMDE5S1aPks5rThPtOL5yx28bPWXVPV74ZesB//pP0BrUOUeBTGj2G20Vvawdtr/C364Iiq1X1RTWZNesKwgRSATOTAzrLLXjNIDB9FCBihsrGi+1Xm+Q4bDr4ciYyTyA2QtKuqzoETbZK8nL
  server.secretkey: AgBziLqNBGv7q45JoO+Px9CADeaMO02V8ZFPCaOrJF77dx6IJtv+Mqs79ZXHyAfRdPn0u6S7VZ24Aq0bDji5/JDiv2eL/Zi93deUbAJawozj21lS+cGGyvuucswDisFmTOr1hU4lsi3J/Z2rZWP5RHoWP1Q+TnklS9td8iDddJdiBPrDCI0BN1PcK2taR8xocQJ2SKE3BgQ0Q8Gd7wdhGBCuDTbznP2i/ME9ocHgzBqpnY9SfDpwUdRlyYoEj6/Ce3hUK5Z9waQbFAO9Sfr2N7A/mvoulLEV0kXCLjZzX3e+2HzjwLJcJwujwCmVp+SvI90U4yqsDIbGnTE1Ql2XPnl0E8bmgX8JoJze5Dd1GW2A+Fsd6s0xhzL3G1w9DirwIiV2sMtlQOzISPwcSnUf9ZF5/QZOMsfV1nJe8OWNnN9BGUVftkL6mmJSv6Z9krRy0W57utPDc/DnqkvBI89FyzeluGWJPBKRfXog+yhohDHB/wm7coMOj+OqVoWmfvGqiyQ8jcc1KYbFaxcHs4YfId1BGMHxKR04HFXgdySRr7AtruWmez9We3zF6FPyGtBzGf+NgRJ7qTzx2KjjBFCuLhXsU1SdNFVyMjtHDQVwpQ9iL+OM9DRd5dIEs6eQ8MSDj0NuZH3e6pZg4tzvhdu8hT1yMdL0GSFDYZY9/dCmb80vnaI9dkhjxtPp7MFZWJPZB8NO7l6SUXaj3ZMRPoJpeX7d4R8IQfqP2zJ4vrIGMkVQ1OnriHN+haaoLQ6/QQ==

encAelabs:
  password: AgCb8WDm0I6DpXqs4ID7KjSzqNGkI+g6fOe/f2fD/k6iFces2SSm0WTHXHEG4JAObYuLnFEYhc+wZGDxFGyuMs49AUTWas3xQRtjUAIM1T4wG0t6sUgBCYxQr89Knf8hP3OjS7aL3+xtVm10t33wE8qTN6rWxeGgLvttlDn+4qjG5LWAmdq3vbRSe2BA0B0MTwd1KbSyoCfBkYjsTFReQDyWOeqkRSM0jIEls15z7cjFDutclzdYCe1BXafznVM3mFkaMP3WmKnXyH1nLOjTrV/qR38w6zW1ilIYEkoTOHpp6tWpFx/hfHnrub0IQzOyDeZdg/tZTYBdHOCLSQGTRB8B9t83QfF+VJaFDwvqPslaRp2QD00klTZGBP1o2MwLptMxt+OyPubEonKLxnrgKhcKTptX/zyCyOp9sRM8r6uH+4t9ukswc1s3k51ZzQfYlk6l29+nSg6LVbVjoDTS+qQfG/4/Eex/pxQmIcKMwYFXEEN3gtwqIOSC8pAZcHEjlfxdoQYA9xFXYNVmAFdydJT5FBQa2U5z6MKn4+J2h86HGPlN8R96ROqRtvnzfWA5e9l8Q8oOlsUu4KNp0d0hvY8uIenN8kquFyRlEo6jWT6YJCYQEmJhn6VBzNQb+qvak2xwjpJh3DzeMaetBas0IlGlMyoF6L9v6tXI91VArQFTMS6Fi+Qzw1MkGr4N8qA+uDpQm0p8M9JpbS4BnOnaD2ZeBBkOhTUFJa4d+hotqsEzEfm54tAv8ft+
  url: AgA9B49iBEoeHs5pOzkFDm0B0Zm/y/4kAXpxgqQ4m5Hr7yJSs1ImWZup8dv5vnphXvSXuEENx4pEEPrgftyYyQA6ErQNEm5750SOuXKjTXVL3oxpDTMFaubxInolbPxKWFRTNOHXJ5qE97wQYqcwLQwCV6eK3FUwLr9sZRYz2S91fNggB2mzQa3ggibOoP2W2uybBkV8UjWWEQUpk+vikR1/hEDrFCNUzQulbjzw4jzJIy3uKqS+IihaifdLBsD6mFFuZbIf51ZWtpA/3x6HdNKruSr2OvtzfAX0p73hg6q7pOPntbTZgFot2e+7ftklFLc4c0yaDzdFdVKlje+eEl3Ba2I2fr/AsbRISJcarhyD7kkD/DcFrMcnWqsloBob0dQVkagwLjbDYwLHQVDQpWp2M3jVOLImq53iYpkmdiWb15nQtIeA2Z4nMLE1zJkxN7ou7dep7L+JEjlSyxvvXzU4w92PfxfZ7rixd7r6uksqCPceH3y1AtZJUJ9oR7l41exi0stXf1qU9xpgl7cPfYuxmXfbEgkffIkGDz49DqIcj62EiigBl+cA3LuSXp8QW958hIjSI+S4ECbuv8iSu/0lb8VT+fat3HSuvS3zgfS8Tse0tPXbrSVKllArRj4PMDtNuMkmskVlQi8Py1xviINLDLpR1LjyksVrw28aDRXxwftlwyGwvpWX14L3sQckK82VM98gsb0nI1rGDSJHBs7Nw5MTPul3/cDkjoTEwM2IGR1N2SH+83lOhwrLzwtlEIU=
  username: AgAKdtb1/JcYVpaNxHnODjxI6ucKwxeFdmoiljk3fvGjWuZxoVCL0tx4YG6eSMEyeX7MbU5cQX65UoiL2+ilCHqFKOw2E3+4SCiRNPdFHTzcLIgPm4x46nX2qZblWnV7cWUlTps2MSZVj5FPw5ZrvHvccKT2J+iV+oEsoKKRgSEacd8AF5Sk8CvmRqaVUdLPKELkbCO//ohnJ1D55Hls3PYV6BI59MTZ0wdMIiTcgCKpmlAoLQ6WuAPUx8Us3sjfJEomq3SAFE2Tq1KFvvDmroiE9JE0VjaUxsj9k2XJ2b6DbTUlWJYRgwvbv0hUtu/nmxuXdAgxBLmfAKJLx2xdW/4AwxEbts2UcpmAwgMBtpAkf3qNP0cQ4wXXt7ehVEPPBMjD5jZO8/UA/VAAswoiw2/rppdMoFJFoEmahAnAA/urOpb07d2LBh+JmZRjyG7C201CjyjvIEDi9rRl6KcLPW9jRqElL3C0ovnkKLI8/c8PV6Iz3T5b2zhwKSUYMtgotBE35G1rsy6rbuHNyHL8bHdiHdzQPphWcq3zIYbBgH86XAgdXGfpEV0ghrLc+A5menjXyaVL4FzvIpzB99cNR0G9y8kczO5+Sk1ypPPOar6RMiT2BcCYNL5SLpEF4nJpPkOQ4jk/kS8O9bs8+1q2r7CS54N1SSZzQM9Kdhcrx+Jm4altELFNR07jm+nd30oThWP+z1EVo59VZEfkBpVfHw==

argo-cd:
  global:
    domain: argocd.prd.service.aepps.com
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      pathType: ImplementationSpecific
      hosts:
        - "argocd.prd.service.aepps.com"
      tls:
        - secretName: traefik-default-cert
          hosts:
            - argocd.prd.service.aepps.com

  configs:
    params:
      server.insecure: true
      applicationsetcontroller.policy: create-update
    cm:
      url: https://argocd.prd.service.aepps.com
      users.anonymous.enabled: "false"
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
                - name: aeternity
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      # url: https://argocd.example.com
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools-superhero.git
        - url: https://github.com/aeternity/gitops-apps-aelabs.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
        - type: helm
          url: https://helm.traefik.io/traefik
          name: traefik
        - type: helm
          url: https://fluent.github.io/helm-charts
          name: fluent
        - type: helm
          url: https://charts.jetstack.io
          name: cert-manager
        - type: helm
          url: https://zekker6.github.io/helm-charts/
          name: plausible
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
        bitnami.com/SealedSecret:
          health.lua: |
            hs = {}
            if obj.status ~= nil and obj.status.conditions ~= nil then
              for _, c in ipairs(obj.status.conditions) do
                if c.type == "Synced" and c.status == "True" then
                  hs.status = "Healthy"
                  hs.message = c.message
                  return hs
                end
              end
            end
            hs.status = "Progressing"
            hs.message = "Waiting for SealedSecret to be unsealed"
            return hs
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, aeternity:devops, role:admin
        
projects:
  - name: tools
    namespace: argocd 
    additionalLabels: {}
    additionalAnnotations: {}
    description: Tools used to run the environment
    sourceRepos:
      - 'https://github.com/aeternity/gitops-tools-superhero.git'
    destinations:
      - namespace: tools
        server: https://kubernetes.default.svc
      - namespace: argocd
        server: https://kubernetes.default.svc
      - namespace: sealed-secrets
        server: https://kubernetes.default.svc
      - namespace: traefik
        server: https://kubernetes.default.svc
      - namespace: kube-system
        server: https://kubernetes.default.svc
      - namespace: monitoring
        server: https://kubernetes.default.svc
      - namespace: logging
        server: https://kubernetes.default.svc
      - namespace: cert-manager
        server: https://kubernetes.default.svc
      - namespace: rabbitmq
        server: https://kubernetes.default.svc
      - namespace: redis
        server: https://kubernetes.default.svc
      - namespace: plausible
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: apps
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Applications deployed on K8S
    sourceRepos:
      - 'https://github.com/aeternity/gitops-apps-aelabs.git'
    destinations:
      - namespace: apps
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'

defaultRepoUrl: 'https://github.com/aeternity/gitops-tools-superhero.git'
defaultTargetRevision: prd

applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
  traefik:
    project: tools
    namespace: traefik
  metrics-server:
    project: tools
    namespace: kube-system
  kube-prometheus-stack:
    project: tools
    namespace: monitoring
  prometheus-blackbox-exporter:
    project: tools
    namespace: monitoring
  hcloud-csi-driver:
    project: tools
    namespace: kube-system
  cert-manager:
    project: tools
    namespace: cert-manager
  rabbitmq:
    project: tools
    namespace: rabbitmq
  redis:
    project: tools
    namespace: redis
  plausible:
    project: tools
    namespace: plausible
  aescan:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  aescan-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  state-channel-demo-frontend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  state-channel-demo-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-wallet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-gateway-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-worker-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-gateway:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-worker:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  governance-server-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  aepp-governance:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
