encValues:
  dex.github.clientID: "AgA9uYL/hlWn45XoUGTWPJ+LY23XGeX3nN5CbIz5XNXxq7KlOdShWz9aCkSWmYGCzrt0bIL5MRlYd+2TW5+G9389HrMdVDFKqa8z1XXANJTzcPnMu6R/V5IcOEsHPZjyk2czY7/roejXaJWdvkbg37bcLJG4dD0VYgPo9T35NvJkDrRCMi5PZF5NXQo6fIvzEoZxp7BDS03bwptSdOAKPR91z8d+9+2bbDjdqGLZN/pRGarWSjac+OVf5VbKcxtRy/caP6yemSzDF0Qqls53pV0qa53Mf4OwbO3O2BLWX2XrWTAPCqtYlThrj/o2oKMeg6o9dOrAN3XNiL3E/9vdyIu6IycJ8jqkbX/4H/jXgqerjm00ZDP17syrpgj5qCnZynAtQy7QPTkbXtTawjZygVlj8/syW428POELGYokOGd6Tx6MNnWACXkuX+llCTbTgvxYTEA70r8FBrQjDqsdp+YdHwDXxY/G4+mXQOsyqO2uw6tBXaLarDqNazFdor2PQtYH/VDqwQnQyC9uXnLTAGCHlpBjfZRCe7wVODXNTv7LqblqUets6WKg7cMa4A+FSp7gyW9E+glSdd72UCXaPa7y1ABXdxW8McbnBvCvJdLnyzfOhXLgxOK4kBkTNUaRi7cYz0Z/tMJoGdOxHkAZv/IGevRo5knDDN0GiT+KKnsuDhlsZK6i1CcUzFT89c2gPjAXDUfgKItV/pQGKQbT6wKEXuuY/Q=="
  dex.github.clientSecret: "AgCcy8+Ovo1RMd3WWKSxowqUspjOfZj5/g5El3+gKK093eIYZb+HO+oAosUcut/piiRLd7idbsSAEGLNzvRyeoHOrzMz8wPzMiSQgCZkauanqkBskTZB90R90L65fG46ycQFMTDPC4Zfa8nK38fP8xwwQOwlZV7S/ry2dnVB4qPtzsA5+90ZHdOteEN725z9Twds1Cxid0MGuJpGDAvI2aEoX3fJqj38Yg/AuFo9kAvbcqNfo98zc0THydc0YLbaIUvUZbm32pUNbS+HA/F8kvGHYwD8iqcOwiRkrp3sItYa8yNOqDqCQGSZ0lkxQZxZx29evQukrI8Tn5PbdysFmUcHSe6wYPtOJ4ZNgbDdPTM5he8WCiAeVj5mRWYuNseTuhntkVWDyRG1P2z9RIwoLYRjbsd/cPLWPBMIlKhgdw6/OHegrXcm6xh4Vq+Kvfg+oE4w3kU9ozEUEJat3+FoEZezDUC2AD7Ro8SxntWWRFMuQQDa9X1CTtnbttAQdvhf6tfwpo20zWFfjm/QbvLJabdXDdvK4bmLt4zODKCyFB5HosxfZP95ydbl6t9TflRfE4TXmDB+0cnLgyPEswAbbWLkZwUxNIctUNfb+XnWxsGNV26cpwIL2a4bcn7BECKm3T2d0K8V4PSL4sTmw5qgWPTvpwUgjFMqbacu9r6T+1/UIiUeW7Wpows0aid2YG/RrJAtRMsJMjERPkIVIbcZjYOq5Dg/j0gKV/YyX9zERtpoY3Lkv5aSDq39"
  server.secretkey: "AgBmoq1btDNPKqZQ44GlOe46FnoAtHL3de+i4inZU0TXZ3/Xm5wtWaYazZ+nxYz3uxz4SP8y5Vp1eVW48eZwN2EL7A/7zBqTzZLOllnou3r2f18mb34aViWw7GU/f4ipg+wGFaFQgDJVs29oyPBzZgt61Dnaw9A8kg18mHjUVZv0oVk7tqhVBLw70aZjrpw9QD0myWUq7Ga7jHfbIWO3wzexuJIAgAROUc0j9y37SQZj/covDybR25dhVMFNiNsFmJgPRz97XdUxZWRCbz3C/unH5M3DQgGQWGd3d6kseZ6QePPi9tZ6aQrtFxdo1Ctp5nkRpdrsyTTQpqQ1qbmUvlqUdQTdIuRlnJjwIQk/NyCyqIkVfNKTFd0MwRLxXVJM/iJw5AKzk1bsKHpoVoKqZPCT8vd2TaudIPY2D/KRECwBXwQHyYu+gqxycAs1PlY04QISECWpoDOcpZ+Ah9NmpRmptUZGBJqe1YIVs5X6CWLUuWh3Jc537nZmWNI1T8AfpRNIka/Bub2n2LXHoLkC3JzVr3N9Oni/+WyevAEptSb41RZiVWVdNFKpa8N3cis2XKwti+pMsZbaahGc1Ejv8YGaIKA6L/VDXncNIxI+ffCrTdZZfAfcgFRFyQ/JlBohWiFjN3H4EGd03mX5AhpdapLPzFLwqIoG74MzoAEp4LtZwm0xI9n54VPiJ1WugH8gkoNVcCQsakf089He3EvHcMd82kzWYQ4qMwpd0a6jyWzOAlBqMuzrGBNChvjfHA=="

encAelabs:
  password: "AgBdrHkg5r1DcnfoiWMwfQb5l3xXsbJDl/I+S8EYDerQbBb9ga/XxVRfOrcTlw/IYH68KRDm+nsTbunrfQ5YUgrR3DBNdVaTZKC91mGgZVzVq2FfMnt0rPEKjCl6PmhN2IEPQPQkvAccIqei31zF5vjQamx8FH6PaOr8q6QyF7FUg5vuRuN6ids6+nbqfZMjfhOPOaIrJT5W9YNgRTYVt0mc1W5tMlXCSEuaoawsVUr+CPHZWzfsA+BXUaQy3vcKEcUWIQ8pw+MJwx6g7WBBuwYUz3c05N1RA7043Sh88MJem1PqTIciUCtONScz6DMD37SFT4+ttP8pTl9fC0WpnRixLLnwcukWRn3b+b8xfX+l/WcoqycTy63/RA1dJpxrvZlGK1pwXlwmWE0U1eUk2WNi5EUwABO/S8AJcnYnFyROf/Vn/ODyyNWAyVXRVnqtp5p0aAmHZHFAhDrhR1Wfn57FcTUbdUs3PSu1t9Zdg9U58/FyFS06+JKUsx62lG0C/lj/HjrM7sGyeG3ukfVVKMXFLFxn1UoAfZ3CpweP10wb1RQqVSEWGoHT73cazwfoH5C+xJSP5bbcxvNgPc+NxMz7+gVCbWIDQxNqlNmV68ZPOYHtXbQgN+3LQk0lH3cM7peNwks3cP97Rq7W5mVrnSFbgsYI4GqCe0QMoMkdk0Km1wRONyL/Sy2Jg3b1oe7lTe07R1qSqdlbR7xSyTE25HYWe3bNShnjJ6HZpenSzYyNPzvr7YNjrstK"
  url: "AgB391Gj4H11P1OiIRxR9S/IF1b9SyJO8669foM66/9rtm5FVZmdg/ij+h8GR/NWFZWB4dPI8OWGC6CBeLi67SJOEuTmGRS32iLC3nfAP/L5b/iD9oJV2UJ9Mo9zsXzX/zG66klfVZVYv3DOGlwJextO//Iz8F6s0kTgcc/5MhIDaU5LMm3EEXqotZiEM/ewaJqC150/U6FXNberj9hqrUCDvV9M6VcUUY6fTiqq+hynSsKEESsFTY+SllaJZvfkXdhLZrMAwaVemOdHtjwyDoeZEmblf1Mu6cgmWQ0IdqSmORYKa8IQYoF0m2R/Xn2Xw5laSBxqhK55KhHYMFq2AVU+XVUHCC3Qw9LszytKKq0/uX1txB3F8zvGfG92c1Ku13AbxxKnw9W+9ZgBuguYHYpt+7E3/p+63cEfIVAFSpAOgQzv6wy8AUfGEYw3qU/l3Izf6iGBkv5kcNZbk7YRZXhNjYDQmue8zAPfUcHpACmASXMuRmI0biL3q9m9T2Kh/3nPmh5IaQVy7mgqnXfbgbiUuyNrNfx8AEEmdgk/cKfRtrgzK/zf2eBVx7G4xA4MHDoZ8TQ0IkvN04EUmiCbPXiE4HQ8XJ1p3WZYSGevOLgmoOyOEVb4m6wTVwnD7IsIOCIxSN5lIfVIRA/oW7lGak9udXpkd5b+JEMKHnI1rR7ftWt1x991hPld5WsfVD5bK7U4x2SVkTj972fkifc0ecR8Xxz1tzHZRqjn5VsVGXLmCgnABdJ+2PsSnFILAAPENdk06MQ="
  username: "AgCT+lE1d4PoBhxBBYXxlR3LmnVGyrYKDiGO0iYtbs5YLLRBG9hINbwWAvQJC40/8hBEX7WtMNPsA0opEeaXp9v4HXgdKZemjgu70pcDv1L2BEQEfye+8p9OTP6tHZnQaNm0GJZnks4I59HIuy2Gsk4FbP/d3KVFDB1Z60qq7g8H118M6x/6RUf9r09+Kciie8JHfaAEgkdHql3cSSR52feW+CwWs9zYQIyd+Nf+fBeSJP9Ygi2oO6jus+EwcEWLgc99CTuwmonw47jIPn1hyRuw0CPSMwywMFuqgbmzni8HSO/wjE7RS6UnTWWXTTtR04lQm5rzEhGLDtn4PckHF7H9fiZhQhh0T8YNy72Lx0VjbNzRANVOorlR1QgKAmHD0fxC60kIB6LLn13sgzOl5xY9+lHfs+BDX9pIV5NgpOH2mFcB0J4qlaE6gYb36McJQXqjem2iTyQKd73mrjbjHDmBTTNWBPUfZeGB15D7BZFtVtrlPfwKknJs/i6ojEyYxPXOo/tgGRQdNjjsiSUQDVD9x0sFFoxRi1bBaObs8ob/00Hgx8+tEnOzyHZ4xNZPq470cqacBqM6cSG+qoXnOGYNS2gW63dffGXWYh+i6qL2FF5DxzM6OwC8wVstogmDOCeMdmP4+hfBoR6gtC9sJ6lxrxSDb0whMn8kiMVokKAHLq/gcV0h0gOok2XM8qfurYyY6xQVSizNIpL7epDM"

argo-cd:
  global:
    domain: argocd.prd.service.aepps.com
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      pathType: ImplementationSpecific
      hosts:
        - "argocd.prd.service.aepps.com"
      tls:
        - secretName: traefik-default-cert
          hosts:
            - argocd.prd.service.aepps.com

  configs:
    params:
      server.insecure: true
      applicationsetcontroller.policy: create-update
    cm:
      url: https://argocd.prd.service.aepps.com
      users.anonymous.enabled: "false"
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
                - name: aeternity
      # Argo CD's externally facing base URL (optional). Required when configuring SSO
      # url: https://argocd.example.com
      application.instanceLabelKey: argocd.argoproj.io/instance
      repositories: |
        - url: https://github.com/aeternity/gitops-tools-superhero.git
        - url: https://github.com/aeternity/gitops-apps-aelabs.git
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
          name: sealed-secrets
        - type: helm
          url: https://helm.traefik.io/traefik
          name: traefik
        - type: helm
          url: https://fluent.github.io/helm-charts
          name: fluent
        - type: helm
          url: https://charts.jetstack.io
          name: cert-manager
        - type: helm
          url: https://zekker6.github.io/helm-charts/
          name: plausible
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
        bitnami.com/SealedSecret:
          health.lua: |
            hs = {}
            if obj.status ~= nil and obj.status.conditions ~= nil then
              for _, c in ipairs(obj.status.conditions) do
                if c.type == "Synced" and c.status == "True" then
                  hs.status = "Healthy"
                  hs.message = c.message
                  return hs
                end
              end
            end
            hs.status = "Progressing"
            hs.message = "Waiting for SealedSecret to be unsealed"
            return hs
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, aeternity:devops, role:admin
        
projects:
  - name: tools
    namespace: argocd 
    additionalLabels: {}
    additionalAnnotations: {}
    description: Tools used to run the environment
    sourceRepos:
      - 'https://github.com/aeternity/gitops-tools-superhero.git'
    destinations:
      - namespace: tools
        server: https://kubernetes.default.svc
      - namespace: argocd
        server: https://kubernetes.default.svc
      - namespace: sealed-secrets
        server: https://kubernetes.default.svc
      - namespace: traefik
        server: https://kubernetes.default.svc
      - namespace: kube-system
        server: https://kubernetes.default.svc
      - namespace: monitoring
        server: https://kubernetes.default.svc
      - namespace: logging
        server: https://kubernetes.default.svc
      - namespace: cert-manager
        server: https://kubernetes.default.svc
      - namespace: rabbitmq
        server: https://kubernetes.default.svc
      - namespace: redis
        server: https://kubernetes.default.svc
      - namespace: plausible
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
  - name: apps
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    description: Applications deployed on K8S
    sourceRepos:
      - 'https://github.com/aeternity/gitops-apps-aelabs.git'
    destinations:
      - namespace: apps
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'

defaultRepoUrl: 'https://github.com/aeternity/gitops-tools-superhero.git'
defaultTargetRevision: prd

applications:
  argocd:
    project: tools
    namespace: argocd
  sealed-secrets:
    project: tools
    namespace: sealed-secrets
  traefik:
    project: tools
    namespace: traefik
  metrics-server:
    project: tools
    namespace: kube-system
  kube-prometheus-stack:
    project: tools
    namespace: monitoring
  prometheus-blackbox-exporter:
    project: tools
    namespace: monitoring
  hcloud-csi-driver:
    project: tools
    namespace: kube-system
  cert-manager:
    project: tools
    namespace: cert-manager
  rabbitmq:
    project: tools
    namespace: rabbitmq
  redis:
    project: tools
    namespace: redis
  plausible:
    project: tools
    namespace: plausible
  aescan:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  aescan-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  state-channel-demo-frontend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  state-channel-demo-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  dex-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-backend-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  ga-multisig-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-ui:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-wallet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-backend:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  superhero-backend-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-gateway-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-worker-testnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-gateway:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  scv-worker:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  governance-server-mainnet:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
  aepp-governance:
    project: apps
    namespace: apps
    repoUrl: 'https://github.com/aeternity/gitops-apps-aelabs.git'
