apiVersion: v2
name: cert-manager-issuers
description: A cert-manager-issuers chart

version: 0.2.4

dependencies:
  - name: cert-manager-issuers
    version: 0.2.4
    repository: https://charts.adfinis.com/
