encValues:
  hcloudApiToken: "AgC/hx3cew0ntrkTR5m7Ot45Y8FvcI/FXQwQgw+qst6mRufAX6e4SJU8skGAPLroTDp2rrUwAem8beYDk/lqKECmdADX5I5SO0E78tUAYssF0VB8I/tb4oJXkBmcpFy2q21TZhgDW3Y4oJ5dHtE6wLyVl8CUVjGsAEuwpsd6G7Sib4R7ufQfNDTV78i9vEhrCdOfVLkN5MZJNyv9aQwBSYgjdr4EMQ772OYgODrL/VL/AWwlGi2C6FzxzFi+P+C5EU/iXWCk5Z1l3NZzngVLO8NQ8U/CxcL9uB5guGJNpcTcAseX+CJ7OW5NlWFAjyPvXfftrgJiJ4Xg+a+u7X5xFcVvB/QYEQ910zADFXjG127tjTUXL413bX0FXx+W0VVGK2iwVMrAi2Xh2qYopMXysmN3C9ix52tv2w3xW2aJfXRZcnwvK/iOMmORQzvjSGpCCxY8xMhEf3/9Q1NWwLNnNPXg5P6MqEVavRgrv2TlKUgOeZjbG+pziIwddv8+6vwYlZRdXjnJ1D/Fur4fAz/FUpWS0B0sKYAQo0NJexaIJhcivqtedye/8mWyzpvLE+lkAfQRYaGk3ZHUnaRRyUhUnuWKGhqRIpCl4uZyw6xQ+gYFjRkLy8EGPi4b+a7BR+NjGJ+77D52qfKqoPGLC/MfDJzYUUnn2iscIz+t0X2PNw9haXqTv1od5shEY+N3LGasTkYVCgNx1NcF0hoygIPKzGRMTGwo3NbmzxJrJ2v1Zf2ZWKpFN1N/Jnd7brX2by+is5RptP+YaRM4eu9UBqeE2zD+"
hcloud-csi:
  controller:
    hcloudToken:
      existingSecret:
        name: hcloud-csi-driver-secret
        key: hcloudApiToken
  storageClasses:
    - name: hcloud-volumes
      defaultStorageClass: true
      reclaimPolicy: Delete
