encValues:
  hcloudApiToken: "AgBs6r73OMdDBn+BhHElRB8MIJDk8U/2QJPCv6MTzhaI/vKvjSKqvgD3nb4DVJKaHJwPdhERB28HdvGiAlfJ9FlGP18gvZkazwnvKReHpIzWHn//XUjFWtfwph43azkf15TMKv1liBQPd+RRFMBOef6SgzpQbsGy1quLPNXCoJr4BLi+aooHDSIRCzT33XY597CM6m3iC6F3sm3qNPzheiYRuYmZ0NQgh6XOAWEe/4HRbijzt/QmrL0jPJi4miVLIMc7F2omGYGGW+rklP9xSEH1+ZAYQf43c3yZKwai4GONRsZUZQxTWUnUHFsGxYfx5O5EVCpS5CCQTM5lblJ3EwZr7PJ/psEm2gERlEJKAhQvuiOu3Zosc7mHKHnTaR5P+DpOlVjSH0LTKn9G0RraU2p710diYA75ZnUX3whCk0XJ86XVFyeRn/0e1pcTsdoNFJsLxTAMRdo05heDks6Mqlnjfdk0QIOQqSn1LB36D8orpuFZTAlXNVw9W+26lNZjRyH8QhDcQ9yMOFAA582RFlv569f0A1uVQhiDy5Iy3ApViRAz2iA8dFHa1B720YEKzYWkzw0czzwyLB5cHHqC9O7/1Xf+GETrkLIiByM9Di2G0+GC7KTwX/FDNLM/3qvfsMq4uhXM/p21fSGvZbj0S7gy2HN3mbesgwSeVSsxmdDET/iV1o4OxGXZgnufvd9uXJPOMGC7+TRH0yygaZOwnYGMOPMeZS33rJFYJFrfu1zQULZ3FTS9ipJoBUjAOB45buMqgmbgErgFzjPqeV11Rmrq"
hcloud-csi-driver:
  # This file is part of the hcloud-csi-driver Helm Chart
  #    https://gitlab.com/MatthiasLohr/hcloud-csi-driver-helm-chart
  #
  # Copyright 2020 Matthias Lohr <mail@mlohr.com>
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #    http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.


  ## Controller configuration
  controller:
    ## hcloud-csi-driver Docker image for controller containers
    image: hetznercloud/hcloud-csi-driver:v2.0.0
    ## ImagePullPolicy for the hcloud-csi-driver Docker image
    imagePullPolicy: IfNotPresent


  ## Node configuration
  node:
    ## hcloud-csi-driver Docker image for node containers
    image: hetznercloud/hcloud-csi-driver:v2.0.0
    ## ImagePullPolicy for the hcloud-csi-driver Docker image
    imagePullPolicy: IfNotPresent
    ## (host) path to kubelet lib dir
    kubeletPath: /var/lib/kubelet

  ## Settings for the StorageClass resource to be created.
  storageClass:
    ## Name of the StorageClass to be created.
    name: hcloud-volume
    ## Should the StorageClass be annotated as default storage class?
    isDefault: true
    ## The reclaimPolicy that the StorageClass should use
    reclaimPolicy: "Delete"

  ## secret for the Hetzner Cloud API token
  secret:
    ## Hetzner Cloud API token
    ## Will be ignored if existingSecretName is set.
    hcloudApiToken:
    # Set this name to use an existing secret.
    # Keep it empty to have a secret generated by this chart.
    existingSecretName: hcloud-csi-driver-secret

  ## Metrics configuration
  metrics:
    ## Enable metrics (create exporters etc.)
    enabled: false
