encValues:
  hcloudApiToken: "AgBRH6XhC723I99XDMDLN+z1GMVy8MKA2aLpvRRV5sdNaFaW/K1UHIPJx+/mKkijhpkIOqTjfvuvkNjvHIxKK9C2jDVT1EE0HD1iuCwajqKjeXxCsFCvHM4tN5Y111cRTYUDChmYKJ5q49TML8+oGvEGeWn4WnofsemvGG38eQORzdp3u4yFrMt0FJmSjAXeDOD2rTwBeHQ1ELmfLpGQjjIuFtEkkbIWRi0KFHaOkOH2l31jmHIcfjXkoFa4qlJX7IUUlrlDcwtkglfOKkvCxUc44sTaSvpC9yaPSBUzWH1/N25XK/3ZAFTFlhLxqqU7+Eyq1ZLjKWRt891V61pKtHMp7siIoVM8BKQYKfqmCbsce624ljWrsWs29xqynj8JXR9/1Kr5JbWuI0SG32SrjSQZiwa1orIkaASJNyz0klkgXR5dXiK4lWMM7zeHiabVkJcdUDcMpmFTthKAEbepUQHWE4Pmqr5tWiWAw8u/flA3RFVruW8GmXRena7Bd42//xH9B3G2pWw9ymHPLQXqUBxBiacMXJD1kUmKfih/GFlww1gTPxOpb5lefUlfqzRafAuxsbbuSprg3IqC1aQGiYsv4b9WQRy/zadogI/HimxXEOUljpqH8+iqW4UAS0h+NSpF1iQWWEGZ9tATirx76Fi3JLvJ0ZZgrUzJPCJQsOHuty7un5dFjikmiT8JFMXxgh00Hfjx+eM7aVuana2ri2wraS8iU95Y8QrtU7rk0yIPfAbqk0oE8SI0IwxhpcCLFhfevodRMvqzyYiMRFV7FEb0"
hcloud-csi:
  controller:
    hcloudToken:
      existingSecret:
        name: hcloud-csi-driver-secret
        key: hcloudApiToken
  storageClasses:
    - name: hcloud-volume
      defaultStorageClass: true
      reclaimPolicy: Delete
