---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-rocketchat-config
  labels:
    alertmanagerConfig: {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: rocketchat
  receivers:
  - name: rocketchat
    webhookConfigs:
      - sendResolved: true
        url: webhook_url
