---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.encValues }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "rabbitmq.labels" . | nindent 8 }}
