encValues:
  accessKeySecret: "AgB/kITl3Rtca7nPfN2O4W8wD01pOF6oX83lY1XFAGO9swbcOgQK8SX3hfCiu6UltvdrGdyxTY7WUUJqASYiNZXAftWcARtEtPT05XAKzVF+sEu5WnNKkZQVo+WGV19t05Pwvs7831OyBT9i1RROLtWMy7zhX0/EjTaodM9G08EKymhcibKwMJVamnpWMkLgepKJm0UmbPIj1OtrcZUQxp44t6PBA4960FYG89MBbiunmHkVzHMNuK+Ojtg7Saj6VB5xFsQZVcHnUZROwd+aaLyyQloq3yka1b3niPSnXq2/pYEoq7BQrfKP9ljc3/zPa6jwsJNJgHfQlgSGnIxYhbqjsbqMx+b7Ejlbu84T9/fQh6LcbiZ7QUPZDdiGwmZBalxFBFg/FVTtaNcd8EXdmntGsHUwfcP/Q3A1tffy0HFifrBg1lo+8AftxGqdN8mdY3FaSij7kjge3sV7TPdV6bOwSu7qzDfgQoOZ3s7A5/NoRwS/KpOzOMj6lLGcFy3bw1v24wtZ2XcUyCYPyjvokrZqDXyvAKiTI8j7gnL+v8q5QXV2Hh+2g2ZGrlhjW50j1RbHS3NIt81krYwZCI3XKVXBc+kRrqYn9PB+SSUlSYlwcy7PKokfkM5F3IFlbGjETVVeLAKyJWw9qlbNpgXGYA5WRlxvU2cLpeFJ/BdzJp0ASh/No3iERVLXk4ceXzEPvBySA/uvnCVDdCjNAEq9dywJc08d3ui50PGOt5HyO6RfCUFdKsdmHB7Z"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
