encValues:
  accessKeySecret: "AgB7dN0LhvT507cANAjaaLpUtf8HgbjY8nQwYk8bFNeauUUg4gs4uhrocLDQ4WlRSYfk609+NRHrYszvWWvZ3aP4l0Bo6f8FKVo1gKjmLHPyDRIrUA1Yw7lgQXxktraC4lYLq++9SXZ8dpsC0qP5iO66O2Fmbtkkx/HqTbbZEaWkerihDu4rkCWd0MAWKxV40qIZ1HMzEwzX7dTA5ouVQL/DtyNLOVKEfs8pvr5si/OvEHHgFPBn+rXSg8sKH5IZfh7Q2xsWRtslP21ElhdqEowzbAPYa7GoEXtCwtTRlY9Rj+mxpLSupHrAEiOH1wPgiYfm8UX/NzXIFZrio/9q/AOO7ef1rj4z7uwlOi6NHvkT34niRPLnGmajS8oK7s/XPx8k8Fj2+8Jl9Q2QBWxGt9yDzaT0a8kRjSCa6BsFGDnTH9bzIXEepRuQdELmBlb46/A796FGyauSjx4lZQoTuS6XkR+TNS0FJwC/WOYJogxWAwVxqkQ4cVZ7YLJEKbo0Dx/kydHzDTpvz3cxHU5FYyiJayrotWmtBJ9AWWGMW8zYT0ZBcei6Z/0tHwrO998rJT/2BRCa0qeu93ttGVmfS2vuL5WWEgROLilmU7kQ1ShBNpPhL31ef0wgWckiQHBul9oCHw3sK3T+b6IEjKw9wS9ITC9SKtW3w5A7BrA3nsRgOtgRT+HUFFAveEOfkOH+8+OjEjXyiqa9/ncEQHk4Pd/iHQFhGiTTyTO0DTnKhwD/7JnnlywTNwwX"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
