encValues:
  accessKeySecret: "AgBsb14+SsDMMkAiNcTIOKiNNwhUZRNdbP3xM03lpehwJRyexoYE0Bl9GRn5PnUWudEOs4iAsNAPsOp8JK8yhlEmz3O3EEpB6wg0sWBgVntFSwVCnRfU/ZG3Vksho5hLuSrnD4zuJAigteRj3yEu8HJgv8L0BCrNCMGTQP9jEs8iEzngaBydSH8Du1jXuZrIAj+O9v10hwVzPZeLB27i+DWe+yGgynBOTD7QMD7ZyK1i0alCXDaFehA0pUoZhaCNuaIxuXRDV4KAX3yWvyDHKqib/pCfMpl6yK7MtJWDBNoUrRL3sflv8UR/4a6cMhWjvxOgMjeLUufENnSLgX64c+I2h5OuKBY60XxPAOytT+3WEcJe9vEJeKg0+BGAxFHsRPkRQ4dZ9PJBA/U+On1avSM2+G2+yObkv1eYM5pwRE/lkcHsbrIj1eNzDccfpvfPRUEmkrWddwO86vM4gsNP6U+xwn2sPABIYnulyOegWc8I3NVPjpx/HY3Ubo3PT3md8qJb96RBTCy7Yt/clwW0tXq+xY2kjuAt0fbhWsVHsokF8bGJvBSpKmEvXAnJHx23ZU+CFvpaDvbgO/H1CRma30i5ExdqdbXxL+swX9eR4wtBNM87jQg7boE6lEiciflS42xzAd/JMbsV7qonlq9IOmlBPFEe2IglfQ6iIHStpehXl2TQstSRk3AG9DDpc2tHrz6EJaGk9l+Kl3xwFSRkFL4zhNoCD9R6vTGSCfqiFoQcopSmEXw71u/I"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
