encValues:
  accessKeySecret: "AgCl9WJy5P7Ki39OmGHhPFC0LQgGy4P11bGyhU49zhbEGl1yT3+sQIxFAx0zSeulqK6QqzZ2OxybSXjNtVW2cua0LW5M1fQcmwUa6slV53LR37S32APJ+T+AWMHII78CitccVHY+BUfBoSPLZ9IjS03WfK+5aUP2jHJ5Bg+y4NcgfIWRP/GIJGV8RFmMD7IgMLDexu8Nt0grLi3vX46KAyoS7cDjgnkQAUSoQ2PEvJ3VJ10qoCOaBJ9KGJwt1O8tw36SKH0at+VtPwCzx/vvLMi2ajZ2oKLnrmnG73IjOTBAa/W35liM6MFCZe2zojvAXB88s2SGfT7GE11OqZgBWXuGFYa4r3l40UXK+NUPwbSHBooSxx6x0+sPzvlWHcMacXzzKLcopGo5x+aCXib3ewWhDA1M/7OGpU6Z7eUb+Fw4tg/77sjs1phrxFvl/D2Q+whJIO6g3hGrSDpjZLhOy5QUs2jdDuCvzLBafuv09cRfK84XVB6sNrVfF38N0fW3zdOpWN3Jp145ZIkIu/3SZ14kRkAf6pNfqt4CdEmKabgzZGBg/43EOgQgWTcMgwcbCxl9YCw9STzXMr4ZnNbmdNqvojptcHEtkEh+qNW+KbcYI2az242HEY7LV8v76hzjGSehYKGpwd7wKcD3QbYLWpH6Dl58UWUXTsMnU8t1HYS2f5PMjmhC3kvU04qed5+J8u2jznkUCP2qOsElOxn8bdNR1FeixsmAVEfFuvD0wn5ZhmshVvu3OC7q"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
