encValues:
  accessKeySecret: "AgCne00VHfPrf8h30p3d60PbkLaRpJBxC6QbR0Ayg10hHdxSRko7gROKnnELk52CM7tNSUsH8hMDoGG5QXC5ASixfbSfnctqBOEvyZ8noMUxcNgj+vrQwZJatmpkT5w9d98/e+SB5haLer9ovWGsOXOibOqdmn+3EaruFyCbMzl9ydOrG5dGctKfpiYb5UFVs6Q4f787GZrx2GzKpMNjzciwQYvkmM7mk6ZDGPu2/PLyIKhhNL4vMZGSLedGD1CxAWOs2EKUMgLjt6WbZ1HiYvoYtFY+OWBUfD9Nl6qi2wTGIKY8MqjNbYqP+HyuHuNVdFsaiZj92gFsWaCD0Q5gfaK23v0g+pscAQuFu/LyxnIGScJTKXsYMxNP3uskUe4LIaji5pQNZJZhJoxMshfhdUPp5q5WKiXiuH94tuG6U70g9hAjBVlkVHm+WT5lg9YD39Pn79s5Sa1Pqm33xBmbo7dTuGIlCX6289mvVQCEaUwTOEL2SzZ2PunWqkfx2c3cUoB7VVScbn8H59y0hiYnBY9xguHn/gAu/dnejcSQ463fR5I2sjye36zPrLrl8nPfP+zVfKtvB3PMJKUxpsrclUGp0K3YhcC9fjSpCzcXSbSxXm4A7xPJ23SX8ij27RRqXaczQt3GtvLO6EUZo9TSNk01Ia/gryP0TmHX/AnDxnSYwIlQbDUAvdCZHaD+4LWMPcugT9wVpZvBzR5C3LNMSseTD2zfZBPF7v0mgc13mz5iQoA3ZlgQKgSY"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
