encValues:
  accessKeySecret: "AgB9lU5K/nJOVQDOw6SKV/snllVKq5+Dczg4LJMHrA8mJkfWb2brzoyE3DIsNggl83kdATXRO/DGBwpv/Xk8ofzscTGCg/1YRno1R9csDPiRVPnfr6fX7SitszjcwuuLXy9h628jivkNx2zuTqWNNlF2GsXC82bBAuSNllQEJnSO0c3lTANnRZr55buCANrAbYl+pqj9LlJJDy2Uyhqm+8XkghZezrpJvl8NJdupLTzGw7+Ap3DPoS7r2onjIjDxUGW53VZDUsDciQANCtvkNxlXoFp2WlK205c7WG2LV+gpgMinPyF/J0ewEFgA7hEre4DSYJfhplFwdP5GWEw2LSZII8t9sK43x4UJhsHeeQTSXujVi7J/fyGTZWzwOCVJj/iPtErZVsEx7uy2MMeY85Q/UIhyaSKZ1Rlw8xn6H4e7x5NI5WzsqifiWTCjYiZZ1tdrD/hUs9wJM//uF1Z5z6D9S8FhN3mZbYGWY/hav5jlHjMwdGSKKp3/DmJAURZyLua9pxvRGTAL0YDGViyDaiQAQLJ5BhyC4vNo3LCbXwODeuwLm//njOTxpF85qP4jiYDBQoG0vfWTbv8HRphG0knN7XnD7rfvQGMUpUp03GOhmdHjuZCy0rtv4bm+ggEwPgNoEmEfb/mTrvGELSav57f204a36kc8MfRsT3PR4ST/GMYzYv3gw/424TyYlgutnaPACMBZsLE0qT8xpvwAfY27WKlprgSX50kq3FKs+H77GOgOxjLtsZGZ"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::106102538874:role/cert-manager-dev"
