encValues:
  accessKeySecret: "AgApOoNdgNwWn7FNwIWyrMSJVBLWlOHWboMpXHhSh6GQqpzn/uoDbLqvAqgZNn5DYIycT2DKDUPUj9956/mm1mhU7qo++QetMhspyXdFS5KgqL27IL4KZMG5n7EVT8z6PmuB7d7paqMunzjzpHU7tErFuHsG34hrfwegjxNllyisXkORCjkQ6txate5XzPYWzug/HqGmBQyf+wMLr796G3LHS7hmotsXwlNwZazkpqwX2LMZLpQ/+77aPK1vkg6SUSPVe/xDLBb+lRcRyQ6z91m7PDGoDmQ2KgXREsbocWmcXMbSjc3z20uTe0Xx6pWB3i7in5YPCpjxX15BPnyslPB7mwHRpVfOTlSarjCpIFzXlPy6NT7qAEtcAqjZj8vkMUDUeubM/8PVu4ze8KVe3qtqV4YLlQsNS3gLhpF8iKDJpo2Rn5IPREGpT1YVp6F2DIOxlPi/EFTWEvw8JyYJ80tst1JdQswFlLIn9dYrmg5k7llWRLnUUzc/0EeNzFe4Hr6cRNyY9rsE+oXQQkiudWFM2dBcKiG1swu67gY+4Phm2qSXrNMY91upvFDkbVkYs50dMEolbEBT8Zj6ygRM2Kzw3GUtPo+wIU6LVykJ180omwT+hfkbaXA8OXP5pJzB8ZwQNox9p9qJbsFltkjNct7VtwfEDGhWiR4D+Srr2eMUtZVU7YnPbQ01PDNdZ8onQoGQVDP8xuieN4s3rx4/0eO2vEWY6DU0OGZ5A82ef64auhoputidy5kq"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
