encValues:
  accessKeySecret: "AgAa+yWzF6KKp/M8W/l0hGHNEm7r8o7ZgGHj5IqOIUre/d+u1boeB+gynmbqI+moWknOjxWQBhh/6ptcp3xxav/VqZTVDZtLfpbQ9WjmoDSKvo9cvw3n4lAMDWHDKujWQu8hcz4Zek/A42EV0yuJb21lb+oOl/NchHOywyWiRX4Fb82h7BbVl2OikejXbMSud/ma/e7p6F7/rRenS/OEzft9FW2eiJI2jQazyMGJDwed4T+waaPywO5xwvYZneZFNW9b4oThX+WsehW4VP9NBwlk6RQ0IMOjUh+KOd7Lpw5EgI+XMiZUQLmrASMZHJhK9EzYo0DZBr230upBiRKVvnGxXN9tgtFvuK0wMTzE49ZaYaFbvhawbYhgmJXn9WA27saF1RqW78KzO21qYSzd80MF53DF570MgzH76lm1I/06h6IufJyK0kKzu2NL+B2Mr+pKdp3lO/FQp5T2cHqpXb0bCnN2k2Q4iUuDtP6EHOTxk9MTTFCEmfyZKuosTnBFu7DM6ZRdeeUJUTnci7Ks0oSEntUiQuUtUzwSU3YY60wCcZfGpEH8cO36oo78vv6UoXHoQ2x7d81xpXI5jk3tloRcWQLVuaVKzr+l3MgQZU1cjWboeqmOQA97XqjaIUs4duzT3LWATI9gbBA2GpVqH6uXVJcPThhpsbvlRCt3WXyw8riIVfSwLUYOUA3IGqMKfJWgQqtzqUIzIvl5B5GBSZAalHVKDr5NlaQcd44FSntXDENGfXtvkCFe"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
