encValues:
  accessKeySecret: "AgAwh7pYLnUVGFrhxypKfIlagMMNpOrVFGy10CblrVHVGIqjGII04D52P9c4hH1Jy+krUfl+vJtEOnk3f6yo4BxiXSD67T1ifKWwmFe/GWFUrtsLL8F6kKHVFgJE7NCtzggglcTdr+uRqfsE1MdU5pADgG0zx0fUusUxp882bpAUUZg4VP3LoSOuMaLgsW1th1zQYEZKEt+ld47J8iJnrIXNZr0yslKJIBIwd0sE+c0PEUYkWJMYv/HH3bVkxn02Pu3dAXdkoLzFFBKDHWsh3A/NKJR1hxi+mvIAqfgjbzDH9uMeAitenprvEb/82pgTIRsRGEdNoYaUl2JLH50E7UZZlCfw09EhjnVcxFPt8R33RXrayLeFGN3wK1uzPL3QJxniqbRjnQPZOvWM5LqROEC8JwzaS9W5qwjo1oSf1/S4VkqKg+IJEsqs3NI8wVywmjrY0HUmjD3neAEjZqq8nOD9lG61kv6+GPqLDR98kmKz+rQaN2d+yhb02T5HIA2ER/jv6ttWYQQ9+WKU/9fWyC2geNp023rV88yWxx83ldgDYVKmYMALJU5Mw3oYoIOsE6Qd1Eep+IPu2FToqcN17hfC1fBywdLkUIMYrpjkufk9V7co4G/DKQpttggcemX3BSXbliZvDKxNS3I5BYbxdqKwisGiMyfNLGkJ4KwK9PO1cCS+QoKx2LotmVNz1uVAYcgQrMRdZsfU6VLiX4ImaR/ewerxkUcXsdFmXWcx3VjyC873WnUgysfd"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
