encValues:
  accessKeySecret: "AgBLGQ90y1skPb7oS8EH2LM3Iu8PNU/zTMX82vIrv3mUCzyUMdOneFw9IvPrjJOzF1WiLDMgTty0CmFn/QQovW6/7nB5oZ63bayOl2nNnJtSf28OD9ySiymXzooGrRNJ0WzFPzWP0e/MsURxyQTutsNaarvNiwS7pVjx7t7/ob6675X45hMp7nAKLO2dYFJg7eRLCt+4oh4W+SvexpSiUC5yn/5Ksa4KoJjxPs+byUsUn9wb9lyYJLSpS2ZENF7EGDZMEBt+cDsU43rQ3InHErpLum8lpR/QpDbn5NFZQpbclMUttQiTrt47Uf4huca2cvGjXPs2UCFN0tBrDF1c4LNjCUsfZGDnuSEFYX9U54qdt2l//cL6J+rMus6R00gyI4u4em/mAsg5gbUX64KqvmpeWku67ToMHFK1nJ+DfJUBtxZ1Kd9PUyr3PCH+u/ZXoVkyup1GerbCbo20EGWfjxINPoKK4cWyBdmKrtr0KIfxh74db0f8ROvpqB3F69CeA0zQYG0d8KotG5qvX3pG7YY12qUVQ+8cvI1xq0O7T15q7wuJlXZhdk3ysO09+5w1WEufZgTQaR+g/q/tp5FcHmqhw0xLxIaDe+RzXKCgVqf23R8g52alTRe8Nw/CcjGf9a75aDFDtmu/aj8LzomqZbIg390qJl0BvqXbuF1gJ8jfshLcbt+bzuxzBrsZmHdD0pHvS7KdOPikPqWAOqZIJ4yVf+CMjGmtskHrQp3JXQt7DHrr7azodQPg"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
