encValues:
  accessKeySecret: "AgCDW0jCWqf2QXZjwpJiPHFw9AItBmMYFpzIPruRQRPDEvFNnhhRwAjiXBjo9Y8DY5EctvcAhEX0o3Q8msScgaBQRepagbic/vVBZHPOWn7v3kdQpIsPEsjjoZe+ehYHeLiAB9BTV++ofvfAJK2sp2p2WZPMUTK72Jjw2nxxqOZ8SSsejEzOq8d2FSM79U7Y5mL481dXSGh98Miu95Dbdqp2zLinlSQYvgZz2GO7+r7EL8kRH/IV3LUN9AddOD2nVYPKgzdOGfRtBFYMKIeuI4j8gJfwN+QvnTZ2YS/9j6tedQTmX2HyasAjsbWfwfe6xQ6Y9ZjTfrw8W72hX3aY8wI4p1TzCIRKyIsnyQ/ksfsNCOfQ1D8r5GVRIo/rdWNMuJd31A8dw0T6FazHSo5IvdwIT20MnrWmjIeMRR1bA5APow0HQbdJ6f5eJkMnY/EAaZljY9GZVB2L4CAqZJCykDhjwtI6wt2rKfUux/FGxuHFzp5xJSerZDWXcpKqOQwEdxfknGvQVP9Fk6Onh4eQBZrjxNQu8xbrtvtzxJsaYqMPft24oxdiCQx6dtmX1ftcJEXNiGBMVzT2T1XsWJNeqgiR3EbuB0zzVaFzEjuFQieD4WJJwyrbpFYklBuEyu6MuKchJlKz+zP/0TkdOg6MyA2YC0XmyAGFrHDpBykBFuq9BZW9z+nuUC46QpWePWHSUryYywbatsJvfWS8xk+18G/oKLFLmGnP5F8XVvS0R3JRGnfdbxBKAdKx"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
