encValues:
  accessKeySecret: "AgAIxzNLpQRWTYx+3tRKOhKRr/pTvpqVx24ZddYCGsAwpAoAEZaZ6Ms5UIngtr9F5ILQ3FEj7lUh9qXf0Rr39+IybxY1FFrzBekuc8o6eEnGE3rwanNx+fVconYIH8Kw0o3aGUilQ2TCZJ9go4vL5qt6gmtPWH0w5rGMn+WQQ3TqpSdFIBdGXzwQFVjxvXj0kyGHC51PtmduDPGNXZkgmKkxVHx1Cmz4RvjRNc5w89YMeHSZdo+NAGyRFE3043ynRQUet2nSSFr2SEE7VEsTdoEu4IdOYU84uIinB7G5XIB/I7y8xGkptcSyDnimq1j/j1tcnl7Ep5h0xX3AMTf//Oj3pjOxXu8tjzSybqVMH2EbNOM1zqlHSDiFgNrAh7yZA0/OCypltuMvqDCIzgLpC8SBWAMCjHe5fr2D4vubA/kw0yn2r0AqGG4ZLcFI9Pixv0RWM/3Dkt8/AlHgu+R+YxRGWQ/SoUyScddl2WSyA3mqYg4Uo+3gOBqbNRe0+62iVH7aSd8XI4qyFS0tFoW4lTKc6LMDuKtVnWOhxfVd+S2IVl1bOi8vjOKEi7uvE42OccuQb60gq0X6MrG3oRtE54nmwfRcUT1jgIL9kAhiEldATJAu5BdIU+FWiocyqFpEffnY/gesUxZg/ffi5s19sPWIyaVygCDfGTxMmHDo64MBcL9T5yTY3vW34YvjwLkMcwiRHMktVVRh3k+0Bljrc7oMqSfMRrv2N/doVzAWnF1eFqaor7Ur+8uF"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
