encValues:
  accessKeySecret: "AgCrgXcLd6GtgdmJP0QOd+TxsHgCM/mWmkcR0MLL7qu386DHAfpH9FFS+g3S2FLYKU5CZpwXuvwN6FQWGlRzHo/Jva3ogcsLdYq0oGKHz9y8eMdAaRc9vFIeVbqoofmiY2HwlktNYwwfqV7HTM5/jF57gjDujpL2NvxyJ0fAfx/DuvDjP0pnOB6cwqmN1j52Ww248YcDbbhM01RyTA/mE/sxO/trkf0iHq+ffk0YVzDNyRRSH91g5b3QoxZAHzKzuGsLtV8/kgERgwE7T62CUtI1gE3v7bqUAOQgpb4+qwOMRUsouTDY8G54bQPV9TCZ3sj4/d0smPpCTILWNy6GBl7Gxr0ZTpm0aojIs9/jsqHFfzeWCvVFf5mLfQVOJRAvdTMS51IhIUvzOREZXjO4Z4kn57i23+OsbMyc3lje8mE/tGacZOfCJg4XeKwx82K17dBq1u0yxOGeCFLQgGNY6nvL+g9tOwh2+4vP1TzM/TiU6IzpCagWIIXJlJg24m7uWJao6y7toHcqwUUrRoseudpvyHOmwkjf3zqCfBGKkuLCYvsENXinfuTJ/WASitsPdnWwF4IBM+yQZ0NJIeOGwPu/qrjwQIh94uyFRWrjKRAmVe254Ec8lMFs6pYQTVRdxuO2wFYApiouTQsK9hgwvamgqskeL7uZ/WqVPireBFKkACKD4dRz6s3LrGnxznJP50sB/mNFAAqt7uYE6Rj2lBSjSoNue2Tp9dClhzYwdAnow5IxQ37dmVsA"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
