encValues:
  accessKeySecret: "AgBsLcGZjDN0URXiDCNM5WPH/o6t2bhULT910xzjy3VzZaF/3vc4w/nMWN1IJtkVU83pVnU8XsoUrMpegxMm0i0essWp9H6/bifYNdrzdo8k+F0YIEN5xQzbcIgnj6wYzvSi946eMsp8yYIkR5DIgsCAUGEYptY+5SS8tzBbwNMzDP1VyEN8j4YcQzkDTIWDrOnDljK58fWNOxUCf0z/+3xJjw4/f6TF8kI+VAa87Tsf8YfJim2ymm761KUk5dLmGFKzPYM/q47MEHOwDppJDSxIz8I98KmB7lD7Z5dFOhvTlYPowry995jhFME3fdWF9RR9w7YHC3McIg0a5iLvTWR51PsJxh4PN1A4ZFD9/LOug+HhWTHIbMESAGbnX8CtpDLWox5yRGQKji+pBw5lTfeLctYW5uafxFkNoNicjPi4ADGJoFPubvYaPygkl+d5IzvcAsd1pRiMAoP9fLRjnx9OMRv2odxH1NnQS1SoNkk95nRdTmrAhvfspUirkZ/qkghkR4XZ8lLQ6uHVPbFq2r6IlDntDRYXT9gB4YW1zSZc+/LEafLeJuxxAGSEv6o6KSTh4v5nqSLhJY7L3XLjzmqdqUVZvYyk/VJjGiWWUQnVfu0rqsgDuy02ferH/mzcsHctykH0GAu1DCwWbcyvJ5M5RtSFX8Jxz658S5AnZGa0gfb5y9Kj1TfQ99QomIlK0GvY2m114/MyHf8GQ9qmzKyCzXo0K3cWAKBHc+ePe7aluNUtRM+4TxHA"

dnsSolverDomains:
  - 'aepps.com'
  
cert-manager:
  installCRDs: true
  securityContext:
    fsGroup: 1001
